# Generated by Django 4.2.8 on 2025-03-21 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rtms",
            name="mt",
        ),
        migrations.AddField(
            model_name="rtms",
            name="total_session",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[django.core.validators.MaxValueValidator(99)],
                verbose_name="Total Session Number",
            ),
        ),
        migrations.AddField(
            model_name="rtmssession",
            name="mt",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="MT",
            ),
        ),
        migrations.AlterField(
            model_name="rtmssession",
            name="session",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(99)],
                verbose_name="شماره ویزیت",
            ),
        ),
    ]
