# Generated by Django 4.2.8 on 2025-03-21 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms", "0002_remove_rtms_mt_rtms_total_session_rtmssession_mt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rtmssession",
            name="mt_patient",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="MT",
            ),
        ),
    ]
