# Generated by Django 4.2.8 on 2025-03-21 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms", "0005_remove_rtmssession_mt"),
    ]

    operations = [
        migrations.AddField(
            model_name="rtmssession",
            name="mt",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="Motor Threshold",
            ),
        ),
    ]
