# Generated by Django 4.2.8 on 2025-03-23 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms", "0006_rtmssession_mt"),
    ]

    operations = [
        migrations.AddField(
            model_name="rtms",
            name="total_sessions",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[django.core.validators.MaxValueValidator(99)],
                verbose_name="Total Session Number",
            ),
        ),
    ]
