# Generated by Django 4.2.8 on 2025-04-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rtms", "0008_alter_tag_options_remove_rtms_total_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rtms",
            name="total_session",
        ),
    ]
