# Generated by Django 4.2.8 on 2025-05-16 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms", "0010_alter_rtmssession_options_alter_pulsetype_name_fa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rtms",
            name="power",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=100,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="Precent of the MT for other sessions.",
            ),
        ),
    ]
