# Generated by Django 4.2.8 on 2025-05-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rtms", "0011_rtms_power"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rtms",
            name="power",
        ),
    ]
