# Generated by Django 4.2.8 on 2025-05-16 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms", "0012_remove_rtms_power"),
    ]

    operations = [
        migrations.AddField(
            model_name="rtms",
            name="power",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="Precent of the MT for other sessions.",
            ),
        ),
    ]
