# Generated by Django 4.2.8 on 2025-07-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain_name", models.CharField(max_length=255, unique=True)),
                ("customer_name_en", models.CharField(max_length=255)),
                ("customer_name_fa", models.CharField(max_length=255)),
                ("db_name", models.CharField(max_length=255)),
                ("db_user", models.CharField(max_length=255)),
                ("db_password", models.CharField(max_length=255)),
                ("db_host", models.CharField(max_length=255)),
                ("db_port", models.IntegerField()),
            ],
            options={
                "db_table": "customer_config",
            },
        ),
    ]
