# Generated by Django 4.2.8 on 2025-07-01 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_name_en", models.CharField(blank=True, max_length=255)),
                ("doctor_name_fa", models.CharField(blank=True, max_length=255)),
                ("doctor_name_short_en", models.CharField(blank=True, max_length=255)),
                ("doctor_name_short_fa", models.CharField(blank=True, max_length=255)),
                ("clinic_name_en", models.CharField(blank=True, max_length=255)),
                ("clinic_name_fa", models.CharField(blank=True, max_length=255)),
                ("specialty_en", models.CharField(blank=True, max_length=255)),
                ("specialty_fa", models.CharField(blank=True, max_length=255)),
                ("logo_path", models.CharField(max_length=255)),
                ("language_code", models.CharField(max_length=2)),
            ],
            options={
                "db_table": "branding",
            },
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branding",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.branding"
                    ),
                ),
            ],
            options={
                "db_table": "connection",
            },
        ),
        migrations.CreateModel(
            name="DatabaseConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("db_name", models.CharField(max_length=255)),
                ("db_user", models.CharField(max_length=255)),
                ("db_password", models.CharField(max_length=255)),
                ("db_host", models.CharField(max_length=255)),
                ("db_port", models.IntegerField()),
            ],
            options={
                "db_table": "databaseconfig",
            },
        ),
        migrations.CreateModel(
            name="OnlyOfficeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jwt_secret", models.CharField(max_length=255)),
                ("docserver_url", models.URLField()),
                ("allowed_ips", models.JSONField(default=list)),
                ("callback_url", models.URLField()),
                ("patient_data_path", models.CharField(max_length=255)),
                ("jwt_expire", models.IntegerField()),
            ],
            options={
                "db_table": "onlyofficeconfig",
            },
        ),
        migrations.DeleteModel(
            name="CustomerConfig",
        ),
        migrations.AddField(
            model_name="connection",
            name="default_database",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to="core.databaseconfig",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="onlyoffice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to="core.onlyofficeconfig",
            ),
        ),
    ]
