# Generated by Django 4.2.8 on 2025-07-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_branding_connection_databaseconfig_onlyofficeconfig_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connection",
            name="branding",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="default_database",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="onlyoffice",
        ),
        migrations.DeleteModel(
            name="Branding",
        ),
        migrations.DeleteModel(
            name="Connection",
        ),
        migrations.DeleteModel(
            name="DatabaseConfig",
        ),
        migrations.DeleteModel(
            name="OnlyOfficeConfig",
        ),
    ]
