# Generated by Django 4.2.8 on 2025-07-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaseconfig",
            name="db_engine",
            field=models.CharField(default="django.db.backends.mysql", max_length=255),
        ),
        migrations.AddField(
            model_name="databaseconfig",
            name="db_options",
            field=models.JSONField(
                default={"init_command": "SET sql_mode='STRICT_TRANS_TABLES'"}
            ),
        ),
        migrations.AlterField(
            model_name="databaseconfig",
            name="db_host",
            field=models.CharField(default="127.0.0.1", max_length=255),
        ),
        migrations.AlterField(
            model_name="databaseconfig",
            name="db_port",
            field=models.IntegerField(default=3307),
        ),
    ]
