# Generated by Django 4.2.8 on 2025-07-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_databaseconfig_db_engine_databaseconfig_db_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaseconfig",
            name="db_timezone",
            field=models.CharField(default="Asia/Tehran", max_length=100),
        ),
    ]
