# Generated by Django 4.2.8 on 2025-01-08 00:05

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ethnicity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("patient_id", models.PositiveIntegerField(unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("ssn", models.PositiveIntegerField(unique=True)),
                ("birthday", django_jalali.db.models.jDateField(blank=True, null=True)),
                ("ethnicity", models.JSONField(default=dict)),
                ("language", models.CharField(blank=True, max_length=100)),
                ("dominant_hand", models.CharField(blank=True, max_length=50)),
                ("insurance", models.CharField(blank=True, max_length=100)),
                (
                    "payment_label",
                    models.CharField(
                        choices=[
                            ("NC", "No Cost"),
                            ("VIP", "VIP"),
                            ("STD", "Standard"),
                        ],
                        default="STD",
                        max_length=50,
                    ),
                ),
                ("tags", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["first_name", "last_name"],
                        name="identity_pa_first_n_527dfd_idx",
                    ),
                    models.Index(fields=["ssn"], name="identity_pa_ssn_6b8ae7_idx"),
                    models.Index(
                        fields=["patient_id"], name="identity_pa_patient_73c73f_idx"
                    ),
                ],
            },
        ),
    ]
