# Generated by Django 4.2.8 on 2025-01-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="ethnicity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="patient",
            name="ssn",
            field=models.PositiveIntegerField(blank=True, unique=True),
        ),
    ]
