# Generated by Django 4.2.8 on 2025-01-08 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_alter_patient_ethnicity_alter_patient_ssn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="ssn",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Patient ID must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
    ]
