# Generated by Django 4.2.8 on 2025-01-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0004_bloodgroup_educationlevel_gender_insurance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="dominant_hand",
            fields=[
                (
                    "code",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name="bloodgroup",
            name="name",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="educationlevel",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="ethnicity",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="languageoption",
            name="name",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="maritalstatus",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="patient",
            name="dominant_hand",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
