# Generated by Django 4.2.8 on 2025-01-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0005_dominant_hand_alter_bloodgroup_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="insurance",
        ),
    ]
