# Generated by Django 4.2.8 on 2025-01-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0007_dominanthand_occupation_delete_dominant_hand_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="dominant_hand",
            new_name="dominanthand",
        ),
    ]
