# Generated by Django 4.2.8 on 2025-01-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0009_remove_patient_dominanthand_patient_dominant_hand"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bloodgroup",
            old_name="code",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="dominanthand",
            old_name="code",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="educationlevel",
            old_name="code",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="gender",
            old_name="code",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="languageoption",
            old_name="code",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="maritalstatus",
            old_name="code",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="dominant_hand",
            new_name="dominanthand",
        ),
    ]
