# Generated by Django 4.2.8 on 2025-01-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0010_rename_code_bloodgroup_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dominanthand",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
