# Generated by Django 4.2.8 on 2025-01-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0014_remove_patient_secretarytags_patient_secretarytags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="secretarytags",
        ),
    ]
