# Generated by Django 4.2.8 on 2025-01-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0016_patient_secretarytags"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="report",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
