# Generated by Django 4.2.8 on 2025-01-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0018_gender_fname"),
    ]

    operations = [
        migrations.AddField(
            model_name="dominanthand",
            name="fname",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="educationlevel",
            name="fname",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
