# Generated by Django 4.2.8 on 2025-01-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "identity",
            "0020_ethnicity_fname_insurance_fname_languageoption_fname_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="patient_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
