# Generated by Django 4.2.8 on 2025-01-27 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0022_occupation_fname_alter_occupation_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="secretarytags",
            new_name="Secretarytags",
        ),
    ]
