# Generated by Django 4.2.8 on 2025-03-17 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0023_rename_secretarytags_patient_secretarytags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must start with 0 and be 11 digits total.",
                        regex="^0\\d{10}$",
                    )
                ],
            ),
        ),
    ]
