# Generated by Django 4.2.8 on 2025-03-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0025_alter_patient_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
