# Generated by Django 4.2.8 on 2025-03-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0026_alter_patient_first_name_alter_patient_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
