# Generated by Django 4.2.8 on 2025-03-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0027_patient_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patient_id_alternative",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
