# Generated by Django 4.2.8 on 2025-05-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0028_patient_patient_id_alternative"),
    ]

    operations = [
        migrations.RenameField(
            model_name="insurance",
            old_name="fname",
            new_name="name_fa",
        ),
    ]
