# Generated by Django 4.2.8 on 2025-05-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0029_rename_fname_insurance_name_fa"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dominanthand",
            old_name="fname",
            new_name="name_fa",
        ),
        migrations.RenameField(
            model_name="educationlevel",
            old_name="fname",
            new_name="name_fa",
        ),
        migrations.RenameField(
            model_name="ethnicity",
            old_name="fname",
            new_name="name_fa",
        ),
        migrations.RenameField(
            model_name="gender",
            old_name="fname",
            new_name="name_fa",
        ),
        migrations.RenameField(
            model_name="languageoption",
            old_name="fname",
            new_name="name_fa",
        ),
        migrations.RenameField(
            model_name="maritalstatus",
            old_name="fname",
            new_name="name_fa",
        ),
        migrations.RenameField(
            model_name="occupation",
            old_name="fname",
            new_name="name_fa",
        ),
    ]
