# Generated by Django 4.2.8 on 2025-07-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branding",
            name="hide_designer",
            field=models.BooleanField(
                default=False, help_text="footer reference to the designer's page"
            ),
        ),
    ]
