# Generated by Django 4.2.8 on 2025-07-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_branding_hide_designer"),
    ]

    operations = [
        migrations.AddField(
            model_name="branding",
            name="slogan1_en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="branding",
            name="slogan1_fa",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="branding",
            name="slogan2_en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="branding",
            name="slogan2_fa",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="branding",
            name="slogan3_en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="branding",
            name="slogan3_fa",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="branding",
            name="slogan4_en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="branding",
            name="slogan4_fa",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
