# Generated by Django 4.2.8 on 2025-07-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_branding_slogan1_en_branding_slogan1_fa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branding",
            name="slogan1_en",
            field=models.CharField(
                blank=True, help_text="title of the first page", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="branding",
            name="slogan1_fa",
            field=models.CharField(
                blank=True, help_text="عنوان صفحه اول", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="branding",
            name="slogan2_en",
            field=models.CharField(
                blank=True, help_text="info of the first page", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="branding",
            name="slogan2_fa",
            field=models.CharField(
                blank=True, help_text="توضیح صفحه اول", max_length=255
            ),
        ),
    ]
