# Generated by Django 4.2.8 on 2025-01-09 09:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0003_alter_patient_ssn"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodGroup",
            fields=[
                (
                    "code",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="EducationLevel",
            fields=[
                (
                    "code",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "code",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.PositiveSmallIntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="LanguageOption",
            fields=[
                (
                    "code",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MaritalStatus",
            fields=[
                (
                    "code",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="patient",
            name="language",
        ),
        migrations.AddField(
            model_name="patient",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="height",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="messenger1",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must start with 0 and be 11 digits total.",
                        regex="^0\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="messenger2",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must start with 0 and be 11 digits total.",
                        regex="^0\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must start with 0 and be 11 digits total.",
                        regex="^0\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="weight",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="blood_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="identity.bloodgroup",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="education_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="identity.educationlevel",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="identity.gender",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="insurances",
            field=models.ManyToManyField(blank=True, to="identity.insurance"),
        ),
        migrations.AddField(
            model_name="patient",
            name="language_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="identity.languageoption",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="marital_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="identity.maritalstatus",
            ),
        ),
    ]
