# Generated by Django 4.2.8 on 2025-01-09 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0006_remove_patient_insurance"),
    ]

    operations = [
        migrations.CreateModel(
            name="DominantHand",
            fields=[
                (
                    "code",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name="dominant_hand",
        ),
        migrations.RemoveField(
            model_name="insurance",
            name="code",
        ),
        migrations.AddField(
            model_name="patient",
            name="edit_history",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="patient",
            name="insurance",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="occupation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="identity.occupation",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="dominant_hand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="identity.dominanthand",
            ),
        ),
    ]
