# Generated by Django 4.2.8 on 2025-01-09 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0008_rename_dominant_hand_patient_dominanthand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="dominanthand",
        ),
        migrations.AddField(
            model_name="patient",
            name="dominant_hand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="identity.dominanthand",
            ),
        ),
    ]
