# Generated by Django 4.2.8 on 2025-01-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0011_alter_dominanthand_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secretarytags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="ethnicity",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
