# Generated by Django 4.2.8 on 2025-01-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0012_secretarytags_alter_ethnicity_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="secretarytags",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
