# Generated by Django 4.2.8 on 2025-01-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0013_patient_secretarytags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="secretarytags",
        ),
        migrations.AddField(
            model_name="patient",
            name="secretarytags",
            field=models.ManyToManyField(blank=True, to="identity.secretarytags"),
        ),
    ]
