# Generated by Django 4.2.8 on 2025-01-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0017_patient_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="gender",
            name="fname",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
