# Generated by Django 4.2.8 on 2025-01-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0019_dominanthand_fname_educationlevel_fname"),
    ]

    operations = [
        migrations.AddField(
            model_name="ethnicity",
            name="fname",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="insurance",
            name="fname",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="languageoption",
            name="fname",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="maritalstatus",
            name="fname",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="ethnicity",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
