# Generated by Django 4.2.8 on 2025-01-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0021_alter_patient_patient_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="occupation",
            name="fname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="occupation",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
