# Generated by Django 4.2.8 on 2025-03-17 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0024_alter_patient_address_alter_patient_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must start with 0 and be 11 digits total.",
                        regex="^0\\d{10}$",
                    )
                ],
            ),
        ),
    ]
