# Generated by Django 4.2.8 on 2025-05-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0030_rename_fname_dominanthand_name_fa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
