# Generated by Django 4.2.8 on 2025-01-28 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0023_rename_secretarytags_patient_secretarytags"),
    ]

    operations = [
        migrations.CreateModel(
            name="PHQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.JSONField(default=dict)),
                ("depression", models.JSONField(default=dict)),
                ("anxiety", models.JSONField(default=dict)),
                ("alcohol", models.JSONField(default=dict)),
                ("eating", models.JSONField(default=dict)),
                ("somatoform", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Moca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.JSONField(default=dict)),
                ("memory", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BloodTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rbc", models.JSONField(default=dict)),
                ("wbc", models.JSONField(default=dict)),
                ("hemoglobin", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                    ),
                ),
            ],
        ),
    ]
