# Generated by Django 4.2.8 on 2025-02-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodtest",
            name="rbc",
        ),
        migrations.AddField(
            model_name="bloodtest",
            name="plt",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="moca",
            name="abstraction",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="moca",
            name="attention",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="moca",
            name="language",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="moca",
            name="naming",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="moca",
            name="orientation",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="moca",
            name="recall",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="moca",
            name="visuospatial",
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name="PHQ",
        ),
    ]
