# Generated by Django 4.2.8 on 2025-02-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0023_rename_secretarytags_patient_secretarytags"),
        ("lab", "0003_category_testmeta"),
    ]

    operations = [
        migrations.CreateModel(
            name="CBC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta", models.JSONField(default=dict)),
                ("WBC", models.JSONField(default=dict)),
                ("RBC", models.JSONField(default=dict)),
                ("hemoglobin", models.JSONField(default=dict)),
                ("hemotocrite", models.JSONField(default=dict)),
                ("MCV", models.JSONField(default=dict)),
                ("MCHC", models.JSONField(default=dict)),
                ("RDW_CV", models.JSONField(default=dict)),
                ("RDW_SD", models.JSONField(default=dict)),
                ("platelets", models.JSONField(default=dict)),
                ("MPV", models.JSONField(default=dict)),
                ("PDW", models.JSONField(default=dict)),
                ("PCT", models.JSONField(default=dict)),
                ("neutrophils", models.JSONField(default=dict)),
                ("lymphocytes", models.JSONField(default=dict)),
                ("monocytes", models.JSONField(default=dict)),
                ("eosinophils", models.JSONField(default=dict)),
                ("basophils", models.JSONField(default=dict)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PHQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta", models.JSONField(default=dict)),
                ("total", models.JSONField(default=dict)),
                ("affective", models.JSONField(default=dict)),
                ("cognitive", models.JSONField(default=dict)),
                ("somatic", models.JSONField(default=dict)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="moca",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="identity.patient"
            ),
        ),
        migrations.DeleteModel(
            name="BloodTest",
        ),
    ]
