# Generated by Django 4.2.8 on 2025-02-09 17:21

import apps.emr.lab.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0023_rename_secretarytags_patient_secretarytags"),
        ("lab", "0005_performer_tag_remove_cbc_meta_remove_moca_meta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cbc",
            name="date",
            field=models.DateField(
                default=apps.emr.lab.models.get_tehran_today, verbose_name="تاریخ انجام"
            ),
        ),
        migrations.AlterField(
            model_name="cbc",
            name="input_date",
            field=models.DateField(
                default=apps.emr.lab.models.get_tehran_today,
                verbose_name="تاریخ وارد کردن",
            ),
        ),
        migrations.AlterField(
            model_name="cbc",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="identity.patient"
            ),
        ),
        migrations.AlterField(
            model_name="cbc",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.performer",
                verbose_name="نام انجام دهنده تست (آزمون گیرنده / آزمایشگاه)",
            ),
        ),
        migrations.AlterField(
            model_name="cbc",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ccpi.session",
                verbose_name="ویزیت",
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="abstraction",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="نمره بخش انتزاع",
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="attention",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="نمره بخش توجه",
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="date",
            field=models.DateField(
                default=apps.emr.lab.models.get_tehran_today, verbose_name="تاریخ انجام"
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="input_date",
            field=models.DateField(
                default=apps.emr.lab.models.get_tehran_today,
                verbose_name="تاریخ وارد کردن",
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="language",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="نمره بخش زبان",
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="memory",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="حافظه",
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="naming",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="نمره بخش نامیدن",
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="orientation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="نمره بخش آگاهی",
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="identity.patient"
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.performer",
                verbose_name="نام انجام دهنده تست (آزمون گیرنده / آزمایشگاه)",
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="recall",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="نمره بخش حافظه",
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ccpi.session",
                verbose_name="ویزیت",
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="نمره کل",
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="visuospatial",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="نمره بخش بصری-موقعیتی",
            ),
        ),
        migrations.AlterField(
            model_name="performer",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                verbose_name="نام انجام دهنده تست (آزمون گیرنده / آزمایشگاه)",
            ),
        ),
        migrations.AlterField(
            model_name="PHQ",
            name="affective",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="نمره بخش روحیه",
            ),
        ),
        migrations.AlterField(
            model_name="PHQ",
            name="cognitive",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="نمره بخش شناخت",
            ),
        ),
        migrations.AlterField(
            model_name="PHQ",
            name="date",
            field=models.DateField(
                default=apps.emr.lab.models.get_tehran_today, verbose_name="تاریخ انجام"
            ),
        ),
        migrations.AlterField(
            model_name="PHQ",
            name="input_date",
            field=models.DateField(
                default=apps.emr.lab.models.get_tehran_today,
                verbose_name="تاریخ وارد کردن",
            ),
        ),
        migrations.AlterField(
            model_name="PHQ",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="identity.patient"
            ),
        ),
        migrations.AlterField(
            model_name="PHQ",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.performer",
                verbose_name="نام انجام دهنده تست (آزمون گیرنده / آزمایشگاه)",
            ),
        ),
        migrations.AlterField(
            model_name="PHQ",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ccpi.session",
                verbose_name="ویزیت",
            ),
        ),
        migrations.AlterField(
            model_name="PHQ",
            name="somatic",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="نمره بخش علائم جسمی",
            ),
        ),
        migrations.AlterField(
            model_name="PHQ",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="نمره کل پرسشنامه کیفیت زندگی",
            ),
        ),
        migrations.AlterField(
            model_name="testmeta",
            name="access",
            field=models.JSONField(default=dict, verbose_name="سطح دسترسی"),
        ),
        migrations.AlterField(
            model_name="testmeta",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="lab.category",
                verbose_name="دسته",
            ),
        ),
    ]
