# Generated by Django 4.2.8 on 2025-02-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0012_remove_cbc_input_date_remove_cbc_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cbc",
            name="platelets",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Platelets"
            ),
        ),
    ]
