# Generated by Django 4.2.8 on 2025-03-03 08:03

import apps.emr.lab.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0023_rename_secretarytags_patient_secretarytags"),
        ("events", "0001_initial"),
        ("lab", "0020_delete_phq"),
    ]

    operations = [
        migrations.CreateModel(
            name="PHQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=apps.emr.lab.models.get_tehran_today,
                        verbose_name="تاریخ انجام",
                    ),
                ),
                (
                    "somatoform",
                    models.BooleanField(
                        default=False, verbose_name="Somatoform Disorder"
                    ),
                ),
                ("major_depression", models.BooleanField(default=False)),
                ("other_depressions", models.BooleanField(default=False)),
                ("panic", models.BooleanField(default=False)),
                ("non_panic_anxiety", models.BooleanField(default=False)),
                ("bulimia", models.BooleanField(default=False)),
                ("binge_eating_disorder", models.BooleanField(default=False)),
                ("alcohol_abuse", models.BooleanField(default=False)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                    ),
                ),
                (
                    "registered_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.event",
                        verbose_name="رویداد ذخیره شده",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lab.tag",
                        verbose_name="برچسب",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
