# Generated by Django 4.2.8 on 2025-03-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0021_phq"),
    ]

    operations = [
        migrations.AddField(
            model_name="phq",
            name="total",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="نمره کل"
            ),
        ),
    ]
