# Generated by Django 4.2.8 on 2025-03-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0022_phq_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phq",
            name="total",
        ),
    ]
