# Generated by Django 4.2.8 on 2025-03-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0026_rename_fname_bloodtestperformer_fa_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
    ]
