# Generated by Django 4.2.8 on 2025-03-09 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0027_alter_tag_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tft",
            name="T4_mol",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="T4 (nmol/l)",
            ),
        ),
        migrations.AddField(
            model_name="tft",
            name="Tg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Thyroglobulin",
            ),
        ),
        migrations.AlterField(
            model_name="tft",
            name="AntiTg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Anti Thyroglobulin Ab",
            ),
        ),
        migrations.AlterField(
            model_name="tft",
            name="T4",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="T4 (mcrg/dl)",
            ),
        ),
    ]
