# Generated by Django 4.2.8 on 2025-03-09 09:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lab", "0028_tft_t4_mol_tft_tg_alter_tft_antitg_alter_tft_t4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="en_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="نام انگلیسی دسته آزمایش",
            ),
        ),
        migrations.AlterField(
            model_name="cbc",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.bloodtestperformer",
                verbose_name="Laboratory Name",
            ),
        ),
        migrations.AlterField(
            model_name="csf",
            name="performer_lab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.bloodtestperformer",
                verbose_name="Laboratory Name",
            ),
        ),
        migrations.AlterField(
            model_name="lft",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.bloodtestperformer",
                verbose_name="Laboratory Name",
            ),
        ),
        migrations.AlterField(
            model_name="lpperformer",
            name="family",
            field=models.CharField(max_length=255, verbose_name="نام خانوادگی:"),
        ),
        migrations.AlterField(
            model_name="lpperformer",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="نام:"),
        ),
        migrations.AlterField(
            model_name="lpperformer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر:",
            ),
        ),
        migrations.AlterField(
            model_name="metabolicprofile",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.bloodtestperformer",
                verbose_name="Laboratory Name",
            ),
        ),
        migrations.AlterField(
            model_name="mmse",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.psychometrician",
                verbose_name="روان سنج",
            ),
        ),
        migrations.AlterField(
            model_name="psychometrician",
            name="family",
            field=models.CharField(max_length=255, verbose_name="نام خانوادگی:"),
        ),
        migrations.AlterField(
            model_name="psychometrician",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="نام:"),
        ),
        migrations.AlterField(
            model_name="psychometrician",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر:",
            ),
        ),
        migrations.AlterField(
            model_name="tft",
            name="TSH",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="TSH",
            ),
        ),
        migrations.AlterField(
            model_name="tft",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.bloodtestperformer",
                verbose_name="Laboratory Name",
            ),
        ),
    ]
