# Generated by Django 4.2.8 on 2025-03-12 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0029_alter_category_en_name_alter_cbc_performer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cbc",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.bloodtestperformer",
                verbose_name="نام آزمایشگاه",
            ),
        ),
        migrations.AlterField(
            model_name="csf",
            name="performer_lab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.bloodtestperformer",
                verbose_name="نام آزمایشگاه",
            ),
        ),
        migrations.AlterField(
            model_name="lft",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.bloodtestperformer",
                verbose_name="نام آزمایشگاه",
            ),
        ),
        migrations.AlterField(
            model_name="metabolicprofile",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.bloodtestperformer",
                verbose_name="نام آزمایشگاه",
            ),
        ),
        migrations.AlterField(
            model_name="tft",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.bloodtestperformer",
                verbose_name="نام آزمایشگاه",
            ),
        ),
    ]
