# Generated by Django 4.2.8 on 2025-03-17 17:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0027_patient_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PulseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام:")),
                ("name_fa", models.CharField(max_length=100, verbose_name="Name (FA)")),
            ],
            options={
                "verbose_name": "Pulse Type",
                "verbose_name_plural": "Pulse Types",
            },
        ),
        migrations.CreateModel(
            name="RTMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mt",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="MT",
                    ),
                ),
                (
                    "first_power",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Precent of the MT for the first session.",
                    ),
                ),
                (
                    "unknown_variable_1",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(99)],
                        verbose_name="unknown_variable_1",
                    ),
                ),
                (
                    "unknown_variable_2",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(99)],
                        verbose_name="unknown_variable_2",
                    ),
                ),
                (
                    "total_pulse",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(99999)],
                        verbose_name="Total Pulse",
                    ),
                ),
                (
                    "dlpfc_l",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="DLPFC Left",
                    ),
                ),
                (
                    "dlpfc_r",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="DLPFC Right",
                    ),
                ),
                (
                    "ofc_l",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="OFC Left",
                    ),
                ),
                (
                    "ofc_r",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="OFC Right",
                    ),
                ),
                (
                    "somatosensory_l",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Somatosensory Left",
                    ),
                ),
                (
                    "somatosensory_r",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Somatosensory Right",
                    ),
                ),
                (
                    "parietal_l",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Parietal Left",
                    ),
                ),
                (
                    "parietal_r",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Parietal Right",
                    ),
                ),
                (
                    "occipital_l",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Occipital Left",
                    ),
                ),
                (
                    "occipital_middle",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Occipital Middle",
                    ),
                ),
                (
                    "occipital_inf",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Occipital Inferior",
                    ),
                ),
                (
                    "occipital_r",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Occipital Right",
                    ),
                ),
                (
                    "m1_l",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="M1 Left",
                    ),
                ),
                (
                    "m1_r",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="M1 Right",
                    ),
                ),
                (
                    "sma_l",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="SMA Left",
                    ),
                ),
                (
                    "sma_r",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="SMA Right",
                    ),
                ),
                (
                    "r_post_central",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Right Post Central",
                    ),
                ),
                (
                    "l_poat_central",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Left Poat Central",
                    ),
                ),
                (
                    "broca_l",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Broca Left",
                    ),
                ),
                (
                    "broca_r",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Broca Right",
                    ),
                ),
                (
                    "sub_temporal_r",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Sub Temporal Right",
                    ),
                ),
                (
                    "sub_temporal_l",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Sub Temporal Left",
                    ),
                ),
                (
                    "middle_temporal_l",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Middle Temporal Left",
                    ),
                ),
                (
                    "middle_temporal_r",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Middle Temporal Right",
                    ),
                ),
                (
                    "identity_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="Patient Identity",
                    ),
                ),
                (
                    "pulse_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rtms.pulsetype",
                        verbose_name="Pulse Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "rTMS",
                "verbose_name_plural": "rTMS",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, null=True, verbose_name="نام:"),
                ),
                (
                    "name_fa",
                    models.CharField(max_length=255, null=True, verbose_name="نام"),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "برچسب ها",
            },
        ),
        migrations.CreateModel(
            name="RTMSSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="شماره ویزیت",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Session Date and Time")),
                ("done", models.BooleanField(default=False, verbose_name="Done")),
                (
                    "power",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Pulse Power"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Session Notes"
                    ),
                ),
                (
                    "identity_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="Patient Identity",
                    ),
                ),
                (
                    "rtms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rtms.rtms",
                        verbose_name="rTMS",
                    ),
                ),
                (
                    "tag",
                    models.ManyToManyField(
                        blank=True, to="rtms.tag", verbose_name="برچسب ها"
                    ),
                ),
            ],
            options={
                "verbose_name": "RTMS Session",
                "verbose_name_plural": "RTMS Sessions",
            },
        ),
    ]
