# Generated by Django 4.2.8 on 2025-03-21 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms", "0003_remove_rtmssession_mt_rtmssession_mt_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rtmssession",
            name="mt_patient",
        ),
        migrations.AlterField(
            model_name="rtmssession",
            name="mt",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="Motor Threshold",
            ),
        ),
    ]
