# Generated by Django 4.2.8 on 2025-03-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rtms", "0004_remove_rtmssession_mt_patient_alter_rtmssession_mt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rtmssession",
            name="mt",
        ),
    ]
