# Generated by Django 4.2.8 on 2025-04-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rtms", "0007_remove_rtms_total_session_rtms_total_sessions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "برچسب", "verbose_name_plural": "برچسب ها"},
        ),
    ]
