# Generated by Django 4.2.8 on 2025-05-02 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtms", "0009_remove_rtms_total_session"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rtmssession",
            options={
                "verbose_name": "جلسه\u200cی rTMS",
                "verbose_name_plural": "جلسات rTMS",
            },
        ),
        migrations.AlterField(
            model_name="pulsetype",
            name="name_fa",
            field=models.CharField(max_length=100, verbose_name="نام:"),
        ),
        migrations.AlterField(
            model_name="rtms",
            name="total_sessions",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[django.core.validators.MaxValueValidator(99)],
                verbose_name="تعداد کل جلسات",
            ),
        ),
        migrations.AlterField(
            model_name="rtmssession",
            name="note",
            field=models.TextField(
                blank=True, null=True, verbose_name="یادداشت\u200cهای جلسه"
            ),
        ),
        migrations.AlterField(
            model_name="rtmssession",
            name="session",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(99)],
                verbose_name="شماره\u200cی جلسه",
            ),
        ),
    ]
