# Generated by Django 4.2.8 on 2025-07-04 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relative_path",
                    models.CharField(
                        help_text='Path relative to the base data directory, e.g. "12345/reports/scan1.pdf"',
                        max_length=255,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("name_fa", models.CharField(blank=True, max_length=128)),
                ("description", models.TextField(blank=True)),
                ("description_fa", models.TextField(blank=True)),
                (
                    "representative_relative_path",
                    models.CharField(
                        help_text="Subfolder path used to identify this DocumentType",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "File Extension",
                "verbose_name_plural": "File Extensions",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PermissionFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "Permission Flag",
                "verbose_name_plural": "Permission Flags",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PermissionProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProtocolGroupPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flags",
                    models.ManyToManyField(
                        related_name="group_permissions", to="files.permissionflag"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_permissions",
                        to="auth.group",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_permissions",
                        to="files.permissionprotocol",
                    ),
                ),
            ],
            options={
                "unique_together": {("protocol", "group")},
            },
        ),
        migrations.CreateModel(
            name="ProtocolAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path_pattern",
                    models.CharField(
                        help_text="fnmatch glob against Document.relative_path",
                        max_length=255,
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="files.permissionprotocol",
                    ),
                ),
            ],
            options={
                "ordering": ["path_pattern"],
            },
        ),
        migrations.AddField(
            model_name="permissionprotocol",
            name="groups",
            field=models.ManyToManyField(
                related_name="permission_protocols",
                through="files.ProtocolGroupPermission",
                to="auth.group",
            ),
        ),
        migrations.CreateModel(
            name="FilePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_view", models.BooleanField(default=False)),
                ("can_download", models.BooleanField(default=False)),
                ("can_print", models.BooleanField(default=False)),
                ("can_comment", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_fill", models.BooleanField(default=False)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_permissions",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Permission by Group",
                "verbose_name_plural": "File Permissions by Group",
            },
        ),
        migrations.CreateModel(
            name="DocumentAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("edit", "Edited"),
                            ("save", "Saved"),
                            ("comment", "Annotated"),
                            ("download", "Downloaded"),
                            ("print", "Printed"),
                            ("fill", "Filled"),
                        ],
                        max_length=16,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("info", models.JSONField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="files.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="files.documenttype",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="file_extension",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="files.fileextension",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="identity.patient",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="protocol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="files.permissionprotocol",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["patient"], name="files_docum_patient_aaae07_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("patient", "relative_path")},
        ),
    ]
