# Generated by Django 4.2.8 on 2025-05-07 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_document_fileextension_permissionflag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("name_fa", models.CharField(blank=True, max_length=128)),
                ("description", models.TextField(blank=True)),
                ("description_fa", models.TextField(blank=True)),
                (
                    "representative_relative_path",
                    models.CharField(
                        help_text="Subfolder path used to identify this DocumentType",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="file_name",
            field=models.CharField(default="d", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="files.documenttype",
            ),
        ),
    ]
