# Generated by Django 4.2.8 on 2025-02-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0006_alter_cbc_date_alter_cbc_input_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Test Type Name"
                    ),
                ),
                (
                    "fname",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Persian Test Type Name",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="category",
            name="fname",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Persian Test Category Name",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Test Category Name"
            ),
        ),
    ]
