# Generated by Django 4.2.8 on 2025-02-10 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0007_testtype_alter_category_fname_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="testmeta",
            name="testtype",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="lab.testtype",
                verbose_name="Testtype",
            ),
        ),
    ]
