# Generated by Django 4.2.8 on 2025-02-10 16:21

import apps.emr.lab.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_initial"),
        ("identity", "0023_rename_secretarytags_patient_secretarytags"),
        ("lab", "0008_testmeta_testtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodTestPerformer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="نام انجام دهنده تست (آزمون گیرنده / آزمایشگاه)",
                    ),
                ),
                (
                    "fname",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Persian Performer Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blood Test Performer",
                "verbose_name_plural": "Blood Test Performers",
            },
        ),
        migrations.AddField(
            model_name="testtype",
            name="eventtypes",
            field=models.ManyToManyField(
                blank=True,
                related_name="testtypes",
                to="events.eventtype",
                verbose_name="Event Types",
            ),
        ),
        migrations.CreateModel(
            name="Psychometrician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="نام"),
                ),
                (
                    "fanme",
                    models.CharField(max_length=255, verbose_name="Persian Nanme"),
                ),
                ("family", models.CharField(max_length=255, verbose_name="Family")),
                (
                    "ffamily",
                    models.CharField(max_length=255, verbose_name="Persian Family"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="آدرس"
                    ),
                ),
                (
                    "education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.educationlevel",
                        verbose_name="سطح تحصیلات",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "Psychometrician",
                "verbose_name_plural": "Psychometricians",
            },
        ),
        migrations.CreateModel(
            name="LpPerformer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="نام"),
                ),
                (
                    "fanme",
                    models.CharField(max_length=255, verbose_name="Persian Nanme"),
                ),
                ("family", models.CharField(max_length=255, verbose_name="Family")),
                (
                    "ffamily",
                    models.CharField(max_length=255, verbose_name="Persian Family"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="آدرس"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "CSF Test Performer",
                "verbose_name_plural": "CSF Test Performers",
            },
        ),
        migrations.CreateModel(
            name="CSF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=apps.emr.lab.models.get_tehran_today,
                        verbose_name="تاریخ انجام",
                    ),
                ),
                (
                    "input_date",
                    models.DateField(
                        default=apps.emr.lab.models.get_tehran_today,
                        verbose_name="تاریخ وارد کردن",
                    ),
                ),
                (
                    "WBC",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="WBC",
                    ),
                ),
                (
                    "RBC",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="RBC",
                    ),
                ),
                (
                    "neutrophils",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Neutrophils",
                    ),
                ),
                (
                    "lymphocytes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Lymphocytes",
                    ),
                ),
                (
                    "monocytes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Monocytes",
                    ),
                ),
                (
                    "eosinophils",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Eosinophils",
                    ),
                ),
                (
                    "basophils",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Basophils",
                    ),
                ),
                (
                    "glucose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Glucose",
                    ),
                ),
                (
                    "protein",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Protein",
                    ),
                ),
                (
                    "ketone",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Ketone",
                    ),
                ),
                (
                    "AB42",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Amyloid Beta 1-42",
                    ),
                ),
                (
                    "alpha_synuclein",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Alpha Synuclein",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                    ),
                ),
                (
                    "performer_lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lab.bloodtestperformer",
                        verbose_name="Lab Performer",
                    ),
                ),
                (
                    "performer_lp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lab.lpperformer",
                        verbose_name="LP Performer",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ccpi.session",
                        verbose_name="ویزیت",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lab.tag",
                        verbose_name="Tag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="cbc",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.bloodtestperformer",
                verbose_name="نام انجام دهنده تست (آزمون گیرنده / آزمایشگاه)",
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.psychometrician",
                verbose_name="نام انجام دهنده تست (آزمون گیرنده / آزمایشگاه)",
            ),
        ),
        migrations.AlterField(
            model_name="PHQ",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.psychometrician",
                verbose_name="نام انجام دهنده تست (آزمون گیرنده / آزمایشگاه)",
            ),
        ),
        migrations.DeleteModel(
            name="Performer",
        ),
    ]
