# Generated by Django 4.2.8 on 2025-02-10 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("lab", "0010_alter_cbc_options_remove_cbc_session_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cbc",
            name="session",
        ),
        migrations.RemoveField(
            model_name="csf",
            name="session",
        ),
        migrations.RemoveField(
            model_name="moca",
            name="session",
        ),
        migrations.RemoveField(
            model_name="PHQ",
            name="session",
        ),
        migrations.AddField(
            model_name="cbc",
            name="registered_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="Registered Event",
            ),
        ),
        migrations.AddField(
            model_name="csf",
            name="registered_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="Registered Event",
            ),
        ),
        migrations.AddField(
            model_name="moca",
            name="registered_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="Registered Event",
            ),
        ),
        migrations.AddField(
            model_name="PHQ",
            name="registered_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="Registered Event",
            ),
        ),
    ]
