# Generated by Django 4.2.8 on 2025-02-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0011_remove_cbc_session_remove_csf_session_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cbc",
            name="input_date",
        ),
        migrations.RemoveField(
            model_name="cbc",
            name="user",
        ),
        migrations.RemoveField(
            model_name="csf",
            name="input_date",
        ),
        migrations.RemoveField(
            model_name="csf",
            name="user",
        ),
        migrations.RemoveField(
            model_name="lft",
            name="input_date",
        ),
        migrations.RemoveField(
            model_name="lft",
            name="user",
        ),
        migrations.RemoveField(
            model_name="metabolicprofile",
            name="input_date",
        ),
        migrations.RemoveField(
            model_name="metabolicprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="moca",
            name="input_date",
        ),
        migrations.RemoveField(
            model_name="moca",
            name="user",
        ),
        migrations.RemoveField(
            model_name="PHQ",
            name="input_date",
        ),
        migrations.RemoveField(
            model_name="PHQ",
            name="user",
        ),
        migrations.RemoveField(
            model_name="tft",
            name="input_date",
        ),
        migrations.RemoveField(
            model_name="tft",
            name="user",
        ),
    ]
