# Generated by Django 4.2.8 on 2025-02-13 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0013_alter_cbc_platelets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lft",
            name="SGOT",
        ),
        migrations.AlterField(
            model_name="lft",
            name="ALB",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(99)],
                verbose_name="Albumin",
            ),
        ),
        migrations.AlterField(
            model_name="lft",
            name="ALP",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(9990)],
                verbose_name="Alkaline Phosphatase (ALP)",
            ),
        ),
        migrations.AlterField(
            model_name="lft",
            name="GGT",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="GGT (Gamma-Glutamyl Transferase)",
            ),
        ),
        migrations.AlterField(
            model_name="lft",
            name="SGPT",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="SGPT (ALT)",
            ),
        ),
        migrations.AlterField(
            model_name="metabolicprofile",
            name="BS",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="BS (Random Plasma Glucose)",
            ),
        ),
        migrations.AlterField(
            model_name="metabolicprofile",
            name="FBS",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="FBS (Fast Plasma Glucose)",
            ),
        ),
        migrations.AlterField(
            model_name="metabolicprofile",
            name="HDL",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="HDL (High-Density Lipoprotein)",
            ),
        ),
        migrations.AlterField(
            model_name="metabolicprofile",
            name="LDL",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="LDL (Low-Density Lipoprotein)",
            ),
        ),
        migrations.AlterField(
            model_name="metabolicprofile",
            name="OGGT",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="OGTT (Oral Glucose Tolerance Test)",
            ),
        ),
        migrations.AlterField(
            model_name="metabolicprofile",
            name="TC",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="TC (Total Cholesterol)",
            ),
        ),
        migrations.AlterField(
            model_name="metabolicprofile",
            name="TG",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="TG (Triglycerides)",
            ),
        ),
        migrations.AlterField(
            model_name="metabolicprofile",
            name="VLDL",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="VLDL (Low-Density Lipoprotein)",
            ),
        ),
        migrations.AlterField(
            model_name="metabolicprofile",
            name="twohPP",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="2hPP (2-hours Post Prandial Plasma Glucose)",
            ),
        ),
    ]
