# Generated by Django 4.2.8 on 2025-02-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("lab", "0014_remove_lft_sgot_alter_lft_alb_alter_lft_alp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bloodtestperformer",
            options={
                "verbose_name": "آزمایشگاه",
                "verbose_name_plural": "آزمایشگاه ها",
            },
        ),
        migrations.AlterModelOptions(
            name="cbc",
            options={"verbose_name": "شمارش کامل خون"},
        ),
        migrations.AlterModelOptions(
            name="lft",
            options={"verbose_name": "تست های عملکرد کبد"},
        ),
        migrations.AlterModelOptions(
            name="lpperformer",
            options={
                "verbose_name": "آزمایشگاه",
                "verbose_name_plural": "آزمایشگاه ها",
            },
        ),
        migrations.AlterModelOptions(
            name="metabolicprofile",
            options={"verbose_name": "پروفایل متابولیک"},
        ),
        migrations.AlterModelOptions(
            name="psychometrician",
            options={"verbose_name": "روان سنج", "verbose_name_plural": "روان سنج ها"},
        ),
        migrations.AlterField(
            model_name="bloodtestperformer",
            name="fname",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="نام انجام دهنده تست (آزمون گیرنده / آزمایشگاه)",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="fname",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="نام دسته آزمایش",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="نام دسته آزمایش"
            ),
        ),
        migrations.AlterField(
            model_name="cbc",
            name="registered_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="رویداد ذخیره شده",
            ),
        ),
        migrations.AlterField(
            model_name="cbc",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.tag",
                verbose_name="برچسب",
            ),
        ),
        migrations.AlterField(
            model_name="csf",
            name="performer_lp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.lpperformer",
                verbose_name="متخصص انجام دهنده LP",
            ),
        ),
        migrations.AlterField(
            model_name="csf",
            name="registered_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="رویداد ذخیره شده",
            ),
        ),
        migrations.AlterField(
            model_name="csf",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.tag",
                verbose_name="برچسب",
            ),
        ),
        migrations.AlterField(
            model_name="lft",
            name="registered_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="رویداد ذخیره شده",
            ),
        ),
        migrations.AlterField(
            model_name="lft",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.tag",
                verbose_name="برچسب",
            ),
        ),
        migrations.AlterField(
            model_name="lpperformer",
            name="fanme",
            field=models.CharField(max_length=255, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="lpperformer",
            name="ffamily",
            field=models.CharField(max_length=255, verbose_name="نام خانوادگی"),
        ),
        migrations.AlterField(
            model_name="metabolicprofile",
            name="registered_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="رویداد ذخیره شده",
            ),
        ),
        migrations.AlterField(
            model_name="metabolicprofile",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.tag",
                verbose_name="برچسب",
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="registered_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="رویداد ذخیره شده",
            ),
        ),
        migrations.AlterField(
            model_name="moca",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.tag",
                verbose_name="برچسب",
            ),
        ),
        migrations.AlterField(
            model_name="PHQ",
            name="registered_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="رویداد ذخیره شده",
            ),
        ),
        migrations.AlterField(
            model_name="phq",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.tag",
                verbose_name="برچسب",
            ),
        ),
        migrations.AlterField(
            model_name="psychometrician",
            name="fanme",
            field=models.CharField(max_length=255, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="psychometrician",
            name="ffamily",
            field=models.CharField(max_length=255, verbose_name="نام خانوادگی"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="fname",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="نام برچسب",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="نام برچسب"
            ),
        ),
        migrations.AlterField(
            model_name="testmeta",
            name="all_required",
            field=models.BooleanField(
                default=False, verbose_name="همه موارد الزامی است"
            ),
        ),
        migrations.AlterField(
            model_name="testmeta",
            name="fname",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="نام آزمایش",
            ),
        ),
        migrations.AlterField(
            model_name="testmeta",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="نام آزمایش"
            ),
        ),
        migrations.AlterField(
            model_name="testmeta",
            name="testtype",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="lab.testtype",
                verbose_name="نوع آزمایش",
            ),
        ),
        migrations.AlterField(
            model_name="testtype",
            name="eventtypes",
            field=models.ManyToManyField(
                blank=True,
                related_name="testtypes",
                to="events.eventtype",
                verbose_name="نوع ثبت",
            ),
        ),
        migrations.AlterField(
            model_name="testtype",
            name="fname",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="نام نوع آزمایش",
            ),
        ),
        migrations.AlterField(
            model_name="testtype",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="نام نوع آزمایش"
            ),
        ),
        migrations.AlterField(
            model_name="tft",
            name="registered_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="رویداد ذخیره شده",
            ),
        ),
        migrations.AlterField(
            model_name="tft",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.tag",
                verbose_name="برچسب",
            ),
        ),
    ]
