# Generated by Django 4.2.8 on 2025-02-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0015_alter_bloodtestperformer_options_alter_cbc_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="fname",
            new_name="fa_name",
        ),
        migrations.AddField(
            model_name="category",
            name="en_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="English Test Category Name",
            ),
        ),
    ]
