# Generated by Django 4.2.8 on 2025-03-03 07:21

import apps.emr.lab.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("identity", "0023_rename_secretarytags_patient_secretarytags"),
        ("lab", "0016_rename_fname_category_fa_name_category_en_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MMSE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=apps.emr.lab.models.get_tehran_today,
                        verbose_name="تاریخ انجام",
                    ),
                ),
                (
                    "total",
                    models.PositiveSmallIntegerField(verbose_name="Total MMSE Score"),
                ),
                (
                    "affective",
                    models.PositiveSmallIntegerField(verbose_name="نمره بخش روحیه"),
                ),
                (
                    "cognitive",
                    models.PositiveSmallIntegerField(verbose_name="نمره بخش شناخت"),
                ),
                (
                    "somatic",
                    models.PositiveSmallIntegerField(
                        verbose_name="نمره بخش علائم جسمی"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                    ),
                ),
                (
                    "performer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lab.psychometrician",
                        verbose_name="نام انجام دهنده تست (آزمون گیرنده / آزمایشگاه)",
                    ),
                ),
                (
                    "registered_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.event",
                        verbose_name="رویداد ذخیره شده",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lab.tag",
                        verbose_name="برچسب",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="PHQ",
        ),
    ]
