# Generated by Django 4.2.8 on 2025-03-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0017_mmse_delete_phq"),
    ]

    operations = [
        migrations.CreateModel(
            name="PHQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("somatoform", models.BooleanField(default=False)),
                ("major_depression", models.BooleanField(default=False)),
                ("other_depressions", models.BooleanField(default=False)),
                ("panic", models.BooleanField(default=False)),
                ("non_panic_anxiety", models.BooleanField(default=False)),
                ("bulimia", models.BooleanField(default=False)),
                ("binge_eating_disorder", models.BooleanField(default=False)),
                ("alcohol_abuse", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="mmse",
            name="total",
            field=models.PositiveSmallIntegerField(
                verbose_name="نمره کل پرسشنامه کیفیت زندگی"
            ),
        ),
    ]
