# Generated by Django 4.2.8 on 2025-03-03 07:58

import apps.emr.lab.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("identity", "0023_rename_secretarytags_patient_secretarytags"),
        ("lab", "0018_phq_alter_mmse_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="phq",
            name="date",
            field=models.DateField(
                default=apps.emr.lab.models.get_tehran_today, verbose_name="تاریخ انجام"
            ),
        ),
        migrations.AddField(
            model_name="phq",
            name="patient",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="identity.patient",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phq",
            name="registered_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="رویداد ذخیره شده",
            ),
        ),
        migrations.AddField(
            model_name="phq",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.tag",
                verbose_name="برچسب",
            ),
        ),
        migrations.AlterField(
            model_name="phq",
            name="somatoform",
            field=models.BooleanField(
                default=False, verbose_name="Somatoform Disorder"
            ),
        ),
    ]
