# Generated by Django 4.2.8 on 2025-03-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0019_phq_date_phq_patient_phq_registered_event_phq_tag_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PHQ",
        ),
    ]
