# Generated by Django 4.2.8 on 2025-03-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0023_remove_phq_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cbc",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="csf",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="lft",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="metabolicprofile",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="mmse",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="moca",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="phq",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="tft",
            name="tag",
        ),
        migrations.AddField(
            model_name="cbc",
            name="tag",
            field=models.ManyToManyField(
                blank=True, to="lab.tag", verbose_name="برچسب ها"
            ),
        ),
        migrations.AddField(
            model_name="csf",
            name="tag",
            field=models.ManyToManyField(
                blank=True, to="lab.tag", verbose_name="برچسب ها"
            ),
        ),
        migrations.AddField(
            model_name="lft",
            name="tag",
            field=models.ManyToManyField(
                blank=True, to="lab.tag", verbose_name="برچسب ها"
            ),
        ),
        migrations.AddField(
            model_name="metabolicprofile",
            name="tag",
            field=models.ManyToManyField(
                blank=True, to="lab.tag", verbose_name="برچسب ها"
            ),
        ),
        migrations.AddField(
            model_name="mmse",
            name="tag",
            field=models.ManyToManyField(
                blank=True, to="lab.tag", verbose_name="برچسب ها"
            ),
        ),
        migrations.AddField(
            model_name="moca",
            name="tag",
            field=models.ManyToManyField(
                blank=True, to="lab.tag", verbose_name="برچسب ها"
            ),
        ),
        migrations.AddField(
            model_name="phq",
            name="tag",
            field=models.ManyToManyField(
                blank=True, to="lab.tag", verbose_name="برچسب ها"
            ),
        ),
        migrations.AddField(
            model_name="tft",
            name="tag",
            field=models.ManyToManyField(
                blank=True, to="lab.tag", verbose_name="برچسب ها"
            ),
        ),
    ]
