# Generated by Django 4.2.8 on 2025-03-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0024_remove_cbc_tag_remove_csf_tag_remove_lft_tag_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="fname",
            new_name="fa_name",
        ),
    ]
