# Generated by Django 4.2.8 on 2025-03-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0025_rename_fname_tag_fa_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bloodtestperformer",
            old_name="fname",
            new_name="fa_name",
        ),
        migrations.RenameField(
            model_name="testmeta",
            old_name="fname",
            new_name="fa_name",
        ),
        migrations.RenameField(
            model_name="testtype",
            old_name="fname",
            new_name="fa_name",
        ),
    ]
