# Generated by Django 4.2.8 on 2025-07-04 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lab", "0001_initial"),
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="McSCISSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "پرسشنامه غربالگری حافظه",
                "verbose_name_plural": "پرسشنامه غربالگری حافظه",
            },
        ),
        migrations.CreateModel(
            name="PHQ010Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Somatoform disorders)",
                "verbose_name_plural": "PHQ Questions (Somatoform disorders)",
            },
        ),
        migrations.CreateModel(
            name="PHQ011Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Somatoform disorders - Severity)",
                "verbose_name_plural": "PHQ Questions (Somatoform disorders - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ020Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Depressive disorders)",
                "verbose_name_plural": "PHQ Questions (Depressive disorders)",
            },
        ),
        migrations.CreateModel(
            name="PHQ021Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Depressive disorders - Severity)",
                "verbose_name_plural": "PHQ Questions (Depressive disorders - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ030Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Panic disorder - part 1)",
                "verbose_name_plural": "PHQ Questions (Panic disorder - part 1)",
            },
        ),
        migrations.CreateModel(
            name="PHQ040Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Panic disorder - part 2)",
                "verbose_name_plural": "PHQ Questions (Panic disorder - part 2)",
            },
        ),
        migrations.CreateModel(
            name="PHQ041Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Panic disorder - Severity)",
                "verbose_name_plural": "PHQ Questions (Panic disorder - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ050Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Anxiety disorders)",
                "verbose_name_plural": "PHQ Questions (Anxiety disorders)",
            },
        ),
        migrations.CreateModel(
            name="PHQ051Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Anxiety disorders - Severity)",
                "verbose_name_plural": "PHQ Questions (Anxiety disorders - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ060Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Eating disorders - part 1)",
                "verbose_name_plural": "PHQ Questions (Eating disorders - part 1)",
            },
        ),
        migrations.CreateModel(
            name="PHQ070Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Eating disorders - part 2)",
                "verbose_name_plural": "PHQ Questions (Eating disorders - part 2)",
            },
        ),
        migrations.CreateModel(
            name="PHQ080Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Eating disorders - part 3)",
                "verbose_name_plural": "PHQ Questions (Eating disorders - part 3)",
            },
        ),
        migrations.CreateModel(
            name="PHQ081Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Eating disorders - Severity)",
                "verbose_name_plural": "PHQ Questions (Eating disorders - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ090Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Alcohol consumption)",
                "verbose_name_plural": "PHQ Questions (Alcohol consumption)",
            },
        ),
        migrations.CreateModel(
            name="PHQ100Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Alcohol abuse disorder)",
                "verbose_name_plural": "PHQ Questions (Alcohol abuse disorder)",
            },
        ),
        migrations.CreateModel(
            name="PHQ101Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Alcohol abuse disorder - Severity)",
                "verbose_name_plural": "PHQ Questions (Alcohol abuse disorder - Severity)",
            },
        ),
        migrations.CreateModel(
            name="YEMSQCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "en_name",
                    models.CharField(max_length=256, verbose_name="پرسش به انگلیسی"),
                ),
                (
                    "fa_name",
                    models.CharField(max_length=256, verbose_name="پرسش به فارسی"),
                ),
                ("description", models.TextField(verbose_name="راهنما")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="YEMSQSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
                (
                    "Category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questionnaires.yemsqcategories",
                        verbose_name="نمره بخش",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرسشنامه طرحواره های ناسازگار اولیه یانگ",
                "verbose_name_plural": "سوالات پرسشنامه طرحواره های ناسازگار اولیه یانگ",
            },
        ),
        migrations.CreateModel(
            name="YEMSQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "q_3",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 3"
                    ),
                ),
                (
                    "q_4",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 4"
                    ),
                ),
                (
                    "q_5",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 5"
                    ),
                ),
                (
                    "q_6",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 6"
                    ),
                ),
                (
                    "q_7",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 7"
                    ),
                ),
                (
                    "q_8",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 8"
                    ),
                ),
                (
                    "q_9",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 9"
                    ),
                ),
                (
                    "q_10",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 10"
                    ),
                ),
                (
                    "q_11",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 11"
                    ),
                ),
                (
                    "q_12",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 12"
                    ),
                ),
                (
                    "q_13",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 13"
                    ),
                ),
                (
                    "q_14",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 14"
                    ),
                ),
                (
                    "q_15",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 15"
                    ),
                ),
                (
                    "q_16",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 16"
                    ),
                ),
                (
                    "q_17",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 17"
                    ),
                ),
                (
                    "q_18",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 18"
                    ),
                ),
                (
                    "q_19",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 19"
                    ),
                ),
                (
                    "q_20",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 20"
                    ),
                ),
                (
                    "q_21",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 21"
                    ),
                ),
                (
                    "q_22",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 22"
                    ),
                ),
                (
                    "q_23",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 23"
                    ),
                ),
                (
                    "q_24",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 24"
                    ),
                ),
                (
                    "q_25",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 25"
                    ),
                ),
                (
                    "q_26",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 26"
                    ),
                ),
                (
                    "q_27",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 27"
                    ),
                ),
                (
                    "q_28",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 28"
                    ),
                ),
                (
                    "q_29",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 29"
                    ),
                ),
                (
                    "q_30",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 30"
                    ),
                ),
                (
                    "q_31",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 31"
                    ),
                ),
                (
                    "q_32",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 32"
                    ),
                ),
                (
                    "q_33",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 33"
                    ),
                ),
                (
                    "q_34",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 34"
                    ),
                ),
                (
                    "q_35",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 35"
                    ),
                ),
                (
                    "q_36",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 36"
                    ),
                ),
                (
                    "q_37",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 37"
                    ),
                ),
                (
                    "q_38",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 38"
                    ),
                ),
                (
                    "q_39",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 39"
                    ),
                ),
                (
                    "q_40",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 40"
                    ),
                ),
                (
                    "q_41",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 41"
                    ),
                ),
                (
                    "q_42",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 42"
                    ),
                ),
                (
                    "q_43",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 43"
                    ),
                ),
                (
                    "q_44",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 44"
                    ),
                ),
                (
                    "q_45",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 45"
                    ),
                ),
                (
                    "q_46",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 46"
                    ),
                ),
                (
                    "q_47",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 47"
                    ),
                ),
                (
                    "q_48",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 48"
                    ),
                ),
                (
                    "q_49",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 49"
                    ),
                ),
                (
                    "q_50",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 50"
                    ),
                ),
                (
                    "q_51",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 51"
                    ),
                ),
                (
                    "q_52",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 52"
                    ),
                ),
                (
                    "q_53",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 53"
                    ),
                ),
                (
                    "q_54",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 54"
                    ),
                ),
                (
                    "q_55",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 55"
                    ),
                ),
                (
                    "q_56",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 56"
                    ),
                ),
                (
                    "q_57",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 57"
                    ),
                ),
                (
                    "q_58",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 58"
                    ),
                ),
                (
                    "q_59",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 59"
                    ),
                ),
                (
                    "q_60",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 60"
                    ),
                ),
                (
                    "q_61",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 61"
                    ),
                ),
                (
                    "q_62",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 62"
                    ),
                ),
                (
                    "q_63",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 63"
                    ),
                ),
                (
                    "q_64",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 64"
                    ),
                ),
                (
                    "q_65",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 65"
                    ),
                ),
                (
                    "q_66",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 66"
                    ),
                ),
                (
                    "q_67",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 67"
                    ),
                ),
                (
                    "q_68",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 68"
                    ),
                ),
                (
                    "q_69",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 69"
                    ),
                ),
                (
                    "q_70",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 70"
                    ),
                ),
                (
                    "q_71",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 71"
                    ),
                ),
                (
                    "q_72",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 72"
                    ),
                ),
                (
                    "q_73",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 73"
                    ),
                ),
                (
                    "q_74",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 74"
                    ),
                ),
                (
                    "q_75",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 75"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "YEMSQ Record",
                "verbose_name_plural": "YEMSQ Records",
            },
        ),
        migrations.CreateModel(
            name="PHQ101",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Alcohol abuse disorder - Severity)",
                "verbose_name_plural": "PHQ Records (Alcohol abuse disorder - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ100",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Alcohol abuse disorder)",
                "verbose_name_plural": "PHQ Records (Alcohol abuse disorder)",
            },
        ),
        migrations.CreateModel(
            name="PHQ090",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Alcohol consumption)",
                "verbose_name_plural": "PHQ Records (Alcohol consumption)",
            },
        ),
        migrations.CreateModel(
            name="PHQ081",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Eating disorders - Severity)",
                "verbose_name_plural": "PHQ Records (Eating disorders - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ080",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Eating disorders - part 3)",
                "verbose_name_plural": "PHQ Records (Eating disorders - part 3)",
            },
        ),
        migrations.CreateModel(
            name="PHQ070",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "q_3",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 3"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Eating disorders - part 2)",
                "verbose_name_plural": "PHQ Records (Eating disorders - part 2)",
            },
        ),
        migrations.CreateModel(
            name="PHQ060",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Eating disorders - part 1)",
                "verbose_name_plural": "PHQ Records (Eating disorders - part 1)",
            },
        ),
        migrations.CreateModel(
            name="PHQ051",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Anxiety disorders - Severity)",
                "verbose_name_plural": "PHQ Records (Anxiety disorders - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ050",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "q_3",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 3"
                    ),
                ),
                (
                    "q_4",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 4"
                    ),
                ),
                (
                    "q_5",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 5"
                    ),
                ),
                (
                    "q_6",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 6"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Anxiety disorders)",
                "verbose_name_plural": "PHQ Records (Anxiety disorders)",
            },
        ),
        migrations.CreateModel(
            name="PHQ041",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Panic disorder - Severity)",
                "verbose_name_plural": "PHQ Records (Panic disorder - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ040",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "q_3",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 3"
                    ),
                ),
                (
                    "q_4",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 4"
                    ),
                ),
                (
                    "q_5",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 5"
                    ),
                ),
                (
                    "q_6",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 6"
                    ),
                ),
                (
                    "q_7",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 7"
                    ),
                ),
                (
                    "q_8",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 8"
                    ),
                ),
                (
                    "q_9",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 9"
                    ),
                ),
                (
                    "q_10",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 10"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Panic disorder - part 2)",
                "verbose_name_plural": "PHQ Records (Panic disorder - part 2)",
            },
        ),
        migrations.CreateModel(
            name="PHQ030",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "q_3",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 3"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Panic disorder - part 1)",
                "verbose_name_plural": "PHQ Records (Panic disorder - part 1)",
            },
        ),
        migrations.CreateModel(
            name="PHQ021",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Depressive disorders - Severity)",
                "verbose_name_plural": "PHQ Records (Depressive disorders - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ020",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "q_3",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 3"
                    ),
                ),
                (
                    "q_4",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 4"
                    ),
                ),
                (
                    "q_5",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 5"
                    ),
                ),
                (
                    "q_6",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 6"
                    ),
                ),
                (
                    "q_7",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 7"
                    ),
                ),
                (
                    "q_8",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 8"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Depressive disorders)",
                "verbose_name_plural": "PHQ Records (Depressive disorders)",
            },
        ),
        migrations.CreateModel(
            name="PHQ011",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Somatoform disorders - Severity)",
                "verbose_name_plural": "PHQ Records (Somatoform disorders - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ010",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "q_3",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 3"
                    ),
                ),
                (
                    "q_4",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 4"
                    ),
                ),
                (
                    "q_5",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 5"
                    ),
                ),
                (
                    "q_6",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 6"
                    ),
                ),
                (
                    "q_7",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 7"
                    ),
                ),
                (
                    "q_8",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 8"
                    ),
                ),
                (
                    "q_9",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 9"
                    ),
                ),
                (
                    "q_10",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 10"
                    ),
                ),
                (
                    "q_11",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 11"
                    ),
                ),
                (
                    "q_12",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 12"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Somatoform disorders)",
                "verbose_name_plural": "PHQ Records (Somatoform disorders)",
            },
        ),
        migrations.CreateModel(
            name="Meta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lowest",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="میزان حداقل"
                    ),
                ),
                (
                    "vector",
                    models.PositiveSmallIntegerField(verbose_name="فاصله بین پاسخ ها"),
                ),
                (
                    "highest",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="میزان حداکثر"
                    ),
                ),
                (
                    "instruction_en",
                    models.TextField(
                        verbose_name="دستورالعمل و معرفی پرسشنامه به انگلیسی"
                    ),
                ),
                (
                    "instruction_fa",
                    models.TextField(
                        verbose_name="دستورالعمل و معرفی پرسشنامه به فارسی"
                    ),
                ),
                (
                    "reference_article",
                    models.CharField(max_length=256, verbose_name="مقاله مرجع"),
                ),
                (
                    "validator_fa",
                    models.CharField(
                        max_length=256,
                        verbose_name="اعتبار سنجی پرسشنامه برای زبان فارسی توسط",
                    ),
                ),
                (
                    "level_1_en",
                    models.CharField(max_length=256, verbose_name="Level 1 in English"),
                ),
                (
                    "level_1_fa",
                    models.CharField(max_length=256, verbose_name="Level 1 in Persian"),
                ),
                (
                    "level_2_en",
                    models.CharField(max_length=256, verbose_name="Level 2 in English"),
                ),
                (
                    "level_2_fa",
                    models.CharField(max_length=256, verbose_name="Level 2 in Persian"),
                ),
                (
                    "level_3_en",
                    models.CharField(max_length=256, verbose_name="Level 3 in English"),
                ),
                (
                    "level_3_fa",
                    models.CharField(max_length=256, verbose_name="Level 3 in Persian"),
                ),
                (
                    "level_4_en",
                    models.CharField(max_length=256, verbose_name="Level 4 in English"),
                ),
                (
                    "level_4_fa",
                    models.CharField(max_length=256, verbose_name="Level 4 in Persian"),
                ),
                (
                    "level_5_en",
                    models.CharField(max_length=256, verbose_name="Level 5 in English"),
                ),
                (
                    "level_5_fa",
                    models.CharField(max_length=256, verbose_name="Level 5 in Persian"),
                ),
                (
                    "level_6_en",
                    models.CharField(max_length=256, verbose_name="Level 6 in English"),
                ),
                (
                    "level_6_fa",
                    models.CharField(max_length=256, verbose_name="Level 6 in Persian"),
                ),
                (
                    "level_7_en",
                    models.CharField(max_length=256, verbose_name="Level 7 in English"),
                ),
                (
                    "level_7_fa",
                    models.CharField(max_length=256, verbose_name="Level 7 in Persian"),
                ),
                (
                    "level_8_en",
                    models.CharField(max_length=256, verbose_name="Level 8 in English"),
                ),
                (
                    "level_8_fa",
                    models.CharField(max_length=256, verbose_name="Level 8 in Persian"),
                ),
                (
                    "level_9_en",
                    models.CharField(max_length=256, verbose_name="Level 9 in English"),
                ),
                (
                    "level_9_fa",
                    models.CharField(max_length=256, verbose_name="Level 9 in Persian"),
                ),
                (
                    "level_10_en",
                    models.CharField(
                        max_length=256, verbose_name="Level 10 in English"
                    ),
                ),
                (
                    "level_10_fa",
                    models.CharField(
                        max_length=256, verbose_name="Level 10 in Persian"
                    ),
                ),
                (
                    "lab_testmeta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lab.testmeta",
                        unique=True,
                        verbose_name="Lab Test Meta ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta",
                "verbose_name_plural": "Meta",
            },
        ),
        migrations.CreateModel(
            name="McSCIS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "q_3",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 3"
                    ),
                ),
                (
                    "q_4",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 4"
                    ),
                ),
                (
                    "q_5",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 5"
                    ),
                ),
                (
                    "q_6",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 6"
                    ),
                ),
                (
                    "q_7",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 7"
                    ),
                ),
                (
                    "q_8",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 8"
                    ),
                ),
                (
                    "q_9",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 9"
                    ),
                ),
                (
                    "q_10",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 10"
                    ),
                ),
                (
                    "q_11",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 11"
                    ),
                ),
                (
                    "q_12",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 12"
                    ),
                ),
                (
                    "q_13",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 13"
                    ),
                ),
                (
                    "q_14",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 14"
                    ),
                ),
                (
                    "q_15",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 15"
                    ),
                ),
                (
                    "q_16",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 16"
                    ),
                ),
                (
                    "q_17",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 17"
                    ),
                ),
                (
                    "q_18",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 18"
                    ),
                ),
                (
                    "q_19",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 19"
                    ),
                ),
                (
                    "q_20",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 20"
                    ),
                ),
                (
                    "q_21",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 21"
                    ),
                ),
                (
                    "q_22",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 22"
                    ),
                ),
                (
                    "q_23",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 23"
                    ),
                ),
                (
                    "q_24",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 24"
                    ),
                ),
                (
                    "q_25",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 25"
                    ),
                ),
                (
                    "q_26",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 26"
                    ),
                ),
                (
                    "q_27",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 27"
                    ),
                ),
                (
                    "q_28",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 28"
                    ),
                ),
                (
                    "q_29",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 29"
                    ),
                ),
                (
                    "q_30",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 30"
                    ),
                ),
                (
                    "q_31",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 31"
                    ),
                ),
                (
                    "q_32",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 32"
                    ),
                ),
                (
                    "q_33",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 33"
                    ),
                ),
                (
                    "q_34",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 34"
                    ),
                ),
                (
                    "q_35",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 35"
                    ),
                ),
                (
                    "q_36",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 36"
                    ),
                ),
                (
                    "q_37",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 37"
                    ),
                ),
                (
                    "q_38",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 38"
                    ),
                ),
                (
                    "q_39",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 39"
                    ),
                ),
                (
                    "q_40",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 40"
                    ),
                ),
                (
                    "q_41",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 41"
                    ),
                ),
                (
                    "q_42",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 42"
                    ),
                ),
                (
                    "q_43",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 43"
                    ),
                ),
                (
                    "q_44",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 44"
                    ),
                ),
                (
                    "q_45",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 45"
                    ),
                ),
                (
                    "q_46",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 46"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "McSCI-S Record",
                "verbose_name_plural": "McSCI-S Records",
            },
        ),
    ]
