# Generated by Django 4.2.8 on 2025-03-10 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meta",
            old_name="lab_testmeta_id",
            new_name="lab_testmeta",
        ),
    ]
