# Generated by Django 4.2.8 on 2025-03-11 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0004_metaq_yemsq_yemsqsheet_delete_meta"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Metaq",
        ),
    ]
