# Generated by Django 4.2.8 on 2025-03-11 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0029_alter_category_en_name_alter_cbc_performer_and_more"),
        ("questionnaires", "0006_metaqu_delete_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lowest",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="میزان حداقل"
                    ),
                ),
                ("vector", models.PositiveSmallIntegerField(verbose_name="Vector")),
                (
                    "highest",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="میزان حداکثر"
                    ),
                ),
                (
                    "instruction_en",
                    models.TextField(
                        verbose_name="دستورالعمل و معرفی پرسشنامه به انگلیسی"
                    ),
                ),
                (
                    "instruction_fa",
                    models.TextField(
                        verbose_name="دستورالعمل و معرفی پرسشنامه به فارسی"
                    ),
                ),
                (
                    "reference_article",
                    models.CharField(max_length=256, verbose_name="مقاله مرجع"),
                ),
                (
                    "validator_fa",
                    models.CharField(
                        max_length=256,
                        verbose_name="اعتبار سنجی پرسشنامه برای زبان فارسی توسط",
                    ),
                ),
                (
                    "level_1_en",
                    models.CharField(max_length=256, verbose_name="Level 1 in English"),
                ),
                (
                    "level_1_fa",
                    models.CharField(max_length=256, verbose_name="Level 1 in Persian"),
                ),
                (
                    "level_2_en",
                    models.CharField(max_length=256, verbose_name="Level 2 in English"),
                ),
                (
                    "level_2_fa",
                    models.CharField(max_length=256, verbose_name="Level 2 in Persian"),
                ),
                (
                    "level_3_en",
                    models.CharField(max_length=256, verbose_name="Level 3 in English"),
                ),
                (
                    "level_3_fa",
                    models.CharField(max_length=256, verbose_name="Level 3 in Persian"),
                ),
                (
                    "level_4_en",
                    models.CharField(max_length=256, verbose_name="Level 4 in English"),
                ),
                (
                    "level_4_fa",
                    models.CharField(max_length=256, verbose_name="Level 4 in Persian"),
                ),
                (
                    "level_5_en",
                    models.CharField(max_length=256, verbose_name="Level 5 in English"),
                ),
                (
                    "level_5_fa",
                    models.CharField(max_length=256, verbose_name="Level 5 in Persian"),
                ),
                (
                    "level_6_en",
                    models.CharField(max_length=256, verbose_name="Level 6 in English"),
                ),
                (
                    "level_6_fa",
                    models.CharField(max_length=256, verbose_name="Level 6 in Persian"),
                ),
                (
                    "level_7_en",
                    models.CharField(max_length=256, verbose_name="Level 7 in English"),
                ),
                (
                    "level_7_fa",
                    models.CharField(max_length=256, verbose_name="Level 7 in Persian"),
                ),
                (
                    "level_8_en",
                    models.CharField(max_length=256, verbose_name="Level 8 in English"),
                ),
                (
                    "level_8_fa",
                    models.CharField(max_length=256, verbose_name="Level 8 in Persian"),
                ),
                (
                    "level_9_en",
                    models.CharField(max_length=256, verbose_name="Level 9 in English"),
                ),
                (
                    "level_9_fa",
                    models.CharField(max_length=256, verbose_name="Level 9 in Persian"),
                ),
                (
                    "level_10_en",
                    models.CharField(
                        max_length=256, verbose_name="Level 10 in English"
                    ),
                ),
                (
                    "level_10_fa",
                    models.CharField(
                        max_length=256, verbose_name="Level 10 in Persian"
                    ),
                ),
                (
                    "lab_testmeta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lab.testmeta",
                        unique=True,
                        verbose_name="Lab Test Meta ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta",
                "verbose_name_plural": "Meta",
            },
        ),
        migrations.DeleteModel(
            name="Metaqu",
        ),
    ]
