# Generated by Django 4.2.8 on 2025-03-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0009_yemsqsheets_delete_yemsqsheet"),
    ]

    operations = [
        migrations.CreateModel(
            name="YEMSQSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
                (
                    "subscore",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="نمره بخش"
                    ),
                ),
                (
                    "en_question_1",
                    models.CharField(max_length=256, verbose_name="English Question 1"),
                ),
                (
                    "fa_question_1",
                    models.CharField(max_length=256, verbose_name="Persian Question 1"),
                ),
                (
                    "en_question_2",
                    models.CharField(max_length=256, verbose_name="English Question 2"),
                ),
                (
                    "fa_question_2",
                    models.CharField(max_length=256, verbose_name="Persian Question 2"),
                ),
                (
                    "en_question_3",
                    models.CharField(max_length=256, verbose_name="English Question 3"),
                ),
                (
                    "fa_question_3",
                    models.CharField(max_length=256, verbose_name="Persian Question 3"),
                ),
                (
                    "en_question_4",
                    models.CharField(max_length=256, verbose_name="English Question 4"),
                ),
                (
                    "fa_question_4",
                    models.CharField(max_length=256, verbose_name="Persian Question 4"),
                ),
                (
                    "en_question_5",
                    models.CharField(max_length=256, verbose_name="English Question 5"),
                ),
                (
                    "fa_question_5",
                    models.CharField(max_length=256, verbose_name="Persian Question 5"),
                ),
                (
                    "en_question_6",
                    models.CharField(max_length=256, verbose_name="English Question 6"),
                ),
                (
                    "fa_question_6",
                    models.CharField(max_length=256, verbose_name="Persian Question 6"),
                ),
                (
                    "en_question_7",
                    models.CharField(max_length=256, verbose_name="English Question 7"),
                ),
                (
                    "fa_question_7",
                    models.CharField(max_length=256, verbose_name="Persian Question 7"),
                ),
                (
                    "en_question_8",
                    models.CharField(max_length=256, verbose_name="English Question 8"),
                ),
                (
                    "fa_question_8",
                    models.CharField(max_length=256, verbose_name="Persian Question 8"),
                ),
                (
                    "en_question_9",
                    models.CharField(max_length=256, verbose_name="English Question 9"),
                ),
                (
                    "fa_question_9",
                    models.CharField(max_length=256, verbose_name="Persian Question 9"),
                ),
                (
                    "en_question_10",
                    models.CharField(
                        max_length=256, verbose_name="English Question 10"
                    ),
                ),
                (
                    "fa_question_10",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 10"
                    ),
                ),
                (
                    "en_question_11",
                    models.CharField(
                        max_length=256, verbose_name="English Question 11"
                    ),
                ),
                (
                    "fa_question_11",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 11"
                    ),
                ),
                (
                    "en_question_12",
                    models.CharField(
                        max_length=256, verbose_name="English Question 12"
                    ),
                ),
                (
                    "fa_question_12",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 12"
                    ),
                ),
                (
                    "en_question_13",
                    models.CharField(
                        max_length=256, verbose_name="English Question 13"
                    ),
                ),
                (
                    "fa_question_13",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 13"
                    ),
                ),
                (
                    "en_question_14",
                    models.CharField(
                        max_length=256, verbose_name="English Question 14"
                    ),
                ),
                (
                    "fa_question_14",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 14"
                    ),
                ),
                (
                    "en_question_15",
                    models.CharField(
                        max_length=256, verbose_name="English Question 15"
                    ),
                ),
                (
                    "fa_question_15",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 15"
                    ),
                ),
                (
                    "en_question_16",
                    models.CharField(
                        max_length=256, verbose_name="English Question 16"
                    ),
                ),
                (
                    "fa_question_16",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 16"
                    ),
                ),
                (
                    "en_question_17",
                    models.CharField(
                        max_length=256, verbose_name="English Question 17"
                    ),
                ),
                (
                    "fa_question_17",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 17"
                    ),
                ),
                (
                    "en_question_18",
                    models.CharField(
                        max_length=256, verbose_name="English Question 18"
                    ),
                ),
                (
                    "fa_question_18",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 18"
                    ),
                ),
                (
                    "en_question_19",
                    models.CharField(
                        max_length=256, verbose_name="English Question 19"
                    ),
                ),
                (
                    "fa_question_19",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 19"
                    ),
                ),
                (
                    "en_question_20",
                    models.CharField(
                        max_length=256, verbose_name="English Question 20"
                    ),
                ),
                (
                    "fa_question_20",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 20"
                    ),
                ),
                (
                    "en_question_21",
                    models.CharField(
                        max_length=256, verbose_name="English Question 21"
                    ),
                ),
                (
                    "fa_question_21",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 21"
                    ),
                ),
                (
                    "en_question_22",
                    models.CharField(
                        max_length=256, verbose_name="English Question 22"
                    ),
                ),
                (
                    "fa_question_22",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 22"
                    ),
                ),
                (
                    "en_question_23",
                    models.CharField(
                        max_length=256, verbose_name="English Question 23"
                    ),
                ),
                (
                    "fa_question_23",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 23"
                    ),
                ),
                (
                    "en_question_24",
                    models.CharField(
                        max_length=256, verbose_name="English Question 24"
                    ),
                ),
                (
                    "fa_question_24",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 24"
                    ),
                ),
                (
                    "en_question_25",
                    models.CharField(
                        max_length=256, verbose_name="English Question 25"
                    ),
                ),
                (
                    "fa_question_25",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 25"
                    ),
                ),
                (
                    "en_question_26",
                    models.CharField(
                        max_length=256, verbose_name="English Question 26"
                    ),
                ),
                (
                    "fa_question_26",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 26"
                    ),
                ),
                (
                    "en_question_27",
                    models.CharField(
                        max_length=256, verbose_name="English Question 27"
                    ),
                ),
                (
                    "fa_question_27",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 27"
                    ),
                ),
                (
                    "en_question_28",
                    models.CharField(
                        max_length=256, verbose_name="English Question 28"
                    ),
                ),
                (
                    "fa_question_28",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 28"
                    ),
                ),
                (
                    "en_question_29",
                    models.CharField(
                        max_length=256, verbose_name="English Question 29"
                    ),
                ),
                (
                    "fa_question_29",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 29"
                    ),
                ),
                (
                    "en_question_30",
                    models.CharField(
                        max_length=256, verbose_name="English Question 30"
                    ),
                ),
                (
                    "fa_question_30",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 30"
                    ),
                ),
                (
                    "en_question_31",
                    models.CharField(
                        max_length=256, verbose_name="English Question 31"
                    ),
                ),
                (
                    "fa_question_31",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 31"
                    ),
                ),
                (
                    "en_question_32",
                    models.CharField(
                        max_length=256, verbose_name="English Question 32"
                    ),
                ),
                (
                    "fa_question_32",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 32"
                    ),
                ),
                (
                    "en_question_33",
                    models.CharField(
                        max_length=256, verbose_name="English Question 33"
                    ),
                ),
                (
                    "fa_question_33",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 33"
                    ),
                ),
                (
                    "en_question_34",
                    models.CharField(
                        max_length=256, verbose_name="English Question 34"
                    ),
                ),
                (
                    "fa_question_34",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 34"
                    ),
                ),
                (
                    "en_question_35",
                    models.CharField(
                        max_length=256, verbose_name="English Question 35"
                    ),
                ),
                (
                    "fa_question_35",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 35"
                    ),
                ),
                (
                    "en_question_36",
                    models.CharField(
                        max_length=256, verbose_name="English Question 36"
                    ),
                ),
                (
                    "fa_question_36",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 36"
                    ),
                ),
                (
                    "en_question_37",
                    models.CharField(
                        max_length=256, verbose_name="English Question 37"
                    ),
                ),
                (
                    "fa_question_37",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 37"
                    ),
                ),
                (
                    "en_question_38",
                    models.CharField(
                        max_length=256, verbose_name="English Question 38"
                    ),
                ),
                (
                    "fa_question_38",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 38"
                    ),
                ),
                (
                    "en_question_39",
                    models.CharField(
                        max_length=256, verbose_name="English Question 39"
                    ),
                ),
                (
                    "fa_question_39",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 39"
                    ),
                ),
                (
                    "en_question_40",
                    models.CharField(
                        max_length=256, verbose_name="English Question 40"
                    ),
                ),
                (
                    "fa_question_40",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 40"
                    ),
                ),
                (
                    "en_question_41",
                    models.CharField(
                        max_length=256, verbose_name="English Question 41"
                    ),
                ),
                (
                    "fa_question_41",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 41"
                    ),
                ),
                (
                    "en_question_42",
                    models.CharField(
                        max_length=256, verbose_name="English Question 42"
                    ),
                ),
                (
                    "fa_question_42",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 42"
                    ),
                ),
                (
                    "en_question_43",
                    models.CharField(
                        max_length=256, verbose_name="English Question 43"
                    ),
                ),
                (
                    "fa_question_43",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 43"
                    ),
                ),
                (
                    "en_question_44",
                    models.CharField(
                        max_length=256, verbose_name="English Question 44"
                    ),
                ),
                (
                    "fa_question_44",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 44"
                    ),
                ),
                (
                    "en_question_45",
                    models.CharField(
                        max_length=256, verbose_name="English Question 45"
                    ),
                ),
                (
                    "fa_question_45",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 45"
                    ),
                ),
                (
                    "en_question_46",
                    models.CharField(
                        max_length=256, verbose_name="English Question 46"
                    ),
                ),
                (
                    "fa_question_46",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 46"
                    ),
                ),
                (
                    "en_question_47",
                    models.CharField(
                        max_length=256, verbose_name="English Question 47"
                    ),
                ),
                (
                    "fa_question_47",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 47"
                    ),
                ),
                (
                    "en_question_48",
                    models.CharField(
                        max_length=256, verbose_name="English Question 48"
                    ),
                ),
                (
                    "fa_question_48",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 48"
                    ),
                ),
                (
                    "en_question_49",
                    models.CharField(
                        max_length=256, verbose_name="English Question 49"
                    ),
                ),
                (
                    "fa_question_49",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 49"
                    ),
                ),
                (
                    "en_question_50",
                    models.CharField(
                        max_length=256, verbose_name="English Question 50"
                    ),
                ),
                (
                    "fa_question_50",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 50"
                    ),
                ),
                (
                    "en_question_51",
                    models.CharField(
                        max_length=256, verbose_name="English Question 51"
                    ),
                ),
                (
                    "fa_question_51",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 51"
                    ),
                ),
                (
                    "en_question_52",
                    models.CharField(
                        max_length=256, verbose_name="English Question 52"
                    ),
                ),
                (
                    "fa_question_52",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 52"
                    ),
                ),
                (
                    "en_question_53",
                    models.CharField(
                        max_length=256, verbose_name="English Question 53"
                    ),
                ),
                (
                    "fa_question_53",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 53"
                    ),
                ),
                (
                    "en_question_54",
                    models.CharField(
                        max_length=256, verbose_name="English Question 54"
                    ),
                ),
                (
                    "fa_question_54",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 54"
                    ),
                ),
                (
                    "en_question_55",
                    models.CharField(
                        max_length=256, verbose_name="English Question 55"
                    ),
                ),
                (
                    "fa_question_55",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 55"
                    ),
                ),
                (
                    "en_question_56",
                    models.CharField(
                        max_length=256, verbose_name="English Question 56"
                    ),
                ),
                (
                    "fa_question_56",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 56"
                    ),
                ),
                (
                    "en_question_57",
                    models.CharField(
                        max_length=256, verbose_name="English Question 57"
                    ),
                ),
                (
                    "fa_question_57",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 57"
                    ),
                ),
                (
                    "en_question_58",
                    models.CharField(
                        max_length=256, verbose_name="English Question 58"
                    ),
                ),
                (
                    "fa_question_58",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 58"
                    ),
                ),
                (
                    "en_question_59",
                    models.CharField(
                        max_length=256, verbose_name="English Question 59"
                    ),
                ),
                (
                    "fa_question_59",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 59"
                    ),
                ),
                (
                    "en_question_60",
                    models.CharField(
                        max_length=256, verbose_name="English Question 60"
                    ),
                ),
                (
                    "fa_question_60",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 60"
                    ),
                ),
                (
                    "en_question_61",
                    models.CharField(
                        max_length=256, verbose_name="English Question 61"
                    ),
                ),
                (
                    "fa_question_61",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 61"
                    ),
                ),
                (
                    "en_question_62",
                    models.CharField(
                        max_length=256, verbose_name="English Question 62"
                    ),
                ),
                (
                    "fa_question_62",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 62"
                    ),
                ),
                (
                    "en_question_63",
                    models.CharField(
                        max_length=256, verbose_name="English Question 63"
                    ),
                ),
                (
                    "fa_question_63",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 63"
                    ),
                ),
                (
                    "en_question_64",
                    models.CharField(
                        max_length=256, verbose_name="English Question 64"
                    ),
                ),
                (
                    "fa_question_64",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 64"
                    ),
                ),
                (
                    "en_question_65",
                    models.CharField(
                        max_length=256, verbose_name="English Question 65"
                    ),
                ),
                (
                    "fa_question_65",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 65"
                    ),
                ),
                (
                    "en_question_66",
                    models.CharField(
                        max_length=256, verbose_name="English Question 66"
                    ),
                ),
                (
                    "fa_question_66",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 66"
                    ),
                ),
                (
                    "en_question_67",
                    models.CharField(
                        max_length=256, verbose_name="English Question 67"
                    ),
                ),
                (
                    "fa_question_67",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 67"
                    ),
                ),
                (
                    "en_question_68",
                    models.CharField(
                        max_length=256, verbose_name="English Question 68"
                    ),
                ),
                (
                    "fa_question_68",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 68"
                    ),
                ),
                (
                    "en_question_69",
                    models.CharField(
                        max_length=256, verbose_name="English Question 69"
                    ),
                ),
                (
                    "fa_question_69",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 69"
                    ),
                ),
                (
                    "en_question_70",
                    models.CharField(
                        max_length=256, verbose_name="English Question 70"
                    ),
                ),
                (
                    "fa_question_70",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 70"
                    ),
                ),
                (
                    "en_question_71",
                    models.CharField(
                        max_length=256, verbose_name="English Question 71"
                    ),
                ),
                (
                    "fa_question_71",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 71"
                    ),
                ),
                (
                    "en_question_72",
                    models.CharField(
                        max_length=256, verbose_name="English Question 72"
                    ),
                ),
                (
                    "fa_question_72",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 72"
                    ),
                ),
                (
                    "en_question_73",
                    models.CharField(
                        max_length=256, verbose_name="English Question 73"
                    ),
                ),
                (
                    "fa_question_73",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 73"
                    ),
                ),
                (
                    "en_question_74",
                    models.CharField(
                        max_length=256, verbose_name="English Question 74"
                    ),
                ),
                (
                    "fa_question_74",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 74"
                    ),
                ),
                (
                    "en_question_75",
                    models.CharField(
                        max_length=256, verbose_name="English Question 75"
                    ),
                ),
                (
                    "fa_question_75",
                    models.CharField(
                        max_length=256, verbose_name="Persian Question 75"
                    ),
                ),
            ],
            options={
                "verbose_name": "YEMSQ Sheet",
                "verbose_name_plural": "YEMSQ Questions",
            },
        ),
        migrations.DeleteModel(
            name="YEMSQSheets",
        ),
    ]
