# Generated by Django 4.2.8 on 2025-03-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0011_delete_yemsqsheet"),
    ]

    operations = [
        migrations.CreateModel(
            name="YEMSQSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "en_question",
                    models.TextField(max_length=256, verbose_name="سوال انگلیسی"),
                ),
                (
                    "fa_question",
                    models.TextField(max_length=256, verbose_name="سوال فارسی"),
                ),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
                (
                    "subscore",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="نمره بخش"
                    ),
                ),
            ],
            options={
                "verbose_name": "YEMSQ Sheet",
                "verbose_name_plural": "YEMSQ Questions",
            },
        ),
    ]
