# Generated by Django 4.2.8 on 2025-03-11 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0023_rename_secretarytags_patient_secretarytags"),
        ("questionnaires", "0013_rename_metaque_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="McSCISSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
                (
                    "subscore",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="نمره بخش"
                    ),
                ),
            ],
            options={
                "verbose_name": "McSCI-S Sheet",
                "verbose_name_plural": "McSCI-S Questions",
            },
        ),
        migrations.AlterModelOptions(
            name="yemsqsheet",
            options={
                "verbose_name": "سوالات پرسشنامه طرحواره های ناسازگار اولیه یانگ",
                "verbose_name_plural": "سوالات پرسشنامه طرحواره های ناسازگار اولیه یانگ",
            },
        ),
        migrations.AlterField(
            model_name="meta",
            name="vector",
            field=models.PositiveSmallIntegerField(verbose_name="فاصله بین پاسخ ها"),
        ),
        migrations.AlterField(
            model_name="yemsq",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ"),
        ),
        migrations.AlterField(
            model_name="yemsqsheet",
            name="en_question",
            field=models.TextField(verbose_name="سوال انگلیسی"),
        ),
        migrations.AlterField(
            model_name="yemsqsheet",
            name="fa_question",
            field=models.TextField(verbose_name="سوال فارسی"),
        ),
        migrations.CreateModel(
            name="McSCIS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "q_3",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 3"
                    ),
                ),
                (
                    "q_4",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 4"
                    ),
                ),
                (
                    "q_5",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 5"
                    ),
                ),
                (
                    "q_6",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 6"
                    ),
                ),
                (
                    "q_7",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 7"
                    ),
                ),
                (
                    "q_8",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 8"
                    ),
                ),
                (
                    "q_9",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 9"
                    ),
                ),
                (
                    "q_10",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 10"
                    ),
                ),
                (
                    "q_11",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 11"
                    ),
                ),
                (
                    "q_12",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 12"
                    ),
                ),
                (
                    "q_13",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 13"
                    ),
                ),
                (
                    "q_14",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 14"
                    ),
                ),
                (
                    "q_15",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 15"
                    ),
                ),
                (
                    "q_16",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 16"
                    ),
                ),
                (
                    "q_17",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 17"
                    ),
                ),
                (
                    "q_18",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 18"
                    ),
                ),
                (
                    "q_19",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 19"
                    ),
                ),
                (
                    "q_20",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 20"
                    ),
                ),
                (
                    "q_21",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 21"
                    ),
                ),
                (
                    "q_22",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 22"
                    ),
                ),
                (
                    "q_23",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 23"
                    ),
                ),
                (
                    "q_24",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 24"
                    ),
                ),
                (
                    "q_25",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 25"
                    ),
                ),
                (
                    "q_26",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 26"
                    ),
                ),
                (
                    "q_27",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 27"
                    ),
                ),
                (
                    "q_28",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 28"
                    ),
                ),
                (
                    "q_29",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 29"
                    ),
                ),
                (
                    "q_30",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 30"
                    ),
                ),
                (
                    "q_31",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 31"
                    ),
                ),
                (
                    "q_32",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 32"
                    ),
                ),
                (
                    "q_33",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 33"
                    ),
                ),
                (
                    "q_34",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 34"
                    ),
                ),
                (
                    "q_35",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 35"
                    ),
                ),
                (
                    "q_36",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 36"
                    ),
                ),
                (
                    "q_37",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 37"
                    ),
                ),
                (
                    "q_38",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 38"
                    ),
                ),
                (
                    "q_39",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 39"
                    ),
                ),
                (
                    "q_40",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 40"
                    ),
                ),
                (
                    "q_41",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 41"
                    ),
                ),
                (
                    "q_42",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 42"
                    ),
                ),
                (
                    "q_43",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 43"
                    ),
                ),
                (
                    "q_44",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 44"
                    ),
                ),
                (
                    "q_45",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 45"
                    ),
                ),
                (
                    "q_46",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 46"
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شماره پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "McSCI-S Record",
                "verbose_name_plural": "McSCI-S Records",
            },
        ),
    ]
