# Generated by Django 4.2.8 on 2025-03-13 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0016_remove_mcscissheet_subscore_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="yemsqsheet",
            options={},
        ),
        migrations.RemoveField(
            model_name="yemsqsheet",
            name="category_content_type",
        ),
        migrations.RemoveField(
            model_name="yemsqsheet",
            name="category_object_id",
        ),
        migrations.RemoveField(
            model_name="yemsqsheet",
            name="coefficient",
        ),
        migrations.RemoveField(
            model_name="yemsqsheet",
            name="en_question",
        ),
        migrations.RemoveField(
            model_name="yemsqsheet",
            name="fa_question",
        ),
        migrations.AddField(
            model_name="yemsqsheet",
            name="description",
            field=models.TextField(
                default=django.utils.timezone.now, verbose_name="Description"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="yemsqsheet",
            name="en_name",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=256,
                verbose_name="English Name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="yemsqsheet",
            name="fa_name",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=256,
                verbose_name="Persian Name",
            ),
            preserve_default=False,
        ),
    ]
