# Generated by Django 4.2.8 on 2025-03-13 23:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("questionnaires", "0017_alter_yemsqsheet_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="YEMSQCategoris",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "en_name",
                    models.CharField(max_length=256, verbose_name="English Name"),
                ),
                (
                    "fa_name",
                    models.CharField(max_length=256, verbose_name="Persian Name"),
                ),
                ("description", models.TextField(verbose_name="Description")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="yemsqsheet",
            options={
                "verbose_name": "پرسشنامه طرحواره های ناسازگار اولیه یانگ",
                "verbose_name_plural": "سوالات پرسشنامه طرحواره های ناسازگار اولیه یانگ",
            },
        ),
        migrations.RemoveField(
            model_name="yemsqsheet",
            name="description",
        ),
        migrations.RemoveField(
            model_name="yemsqsheet",
            name="en_name",
        ),
        migrations.RemoveField(
            model_name="yemsqsheet",
            name="fa_name",
        ),
        migrations.AddField(
            model_name="yemsqsheet",
            name="category_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Category Content Type",
            ),
        ),
        migrations.AddField(
            model_name="yemsqsheet",
            name="category_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="yemsqsheet",
            name="coefficient",
            field=models.SmallIntegerField(default=1, verbose_name="ضریب"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="yemsqsheet",
            name="en_question",
            field=models.TextField(default="", verbose_name="سوال انگلیسی"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="yemsqsheet",
            name="fa_question",
            field=models.TextField(
                default=django.utils.timezone.now, verbose_name="سوال فارسی"
            ),
            preserve_default=False,
        ),
    ]
