# Generated by Django 4.2.8 on 2025-03-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0019_rename_yemsqcategoris_yemsqcategories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yemsqcategories",
            name="description",
            field=models.TextField(verbose_name="راهنما"),
        ),
        migrations.AlterField(
            model_name="yemsqcategories",
            name="en_name",
            field=models.CharField(max_length=256, verbose_name="پرسش به انگلیسی"),
        ),
        migrations.AlterField(
            model_name="yemsqcategories",
            name="fa_name",
            field=models.CharField(max_length=256, verbose_name="پرسش به فارسی"),
        ),
    ]
