# Generated by Django 4.2.8 on 2025-04-15 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0028_patient_patient_id_alternative"),
        ("questionnaires", "0021_alter_mcscis_patient_id_alter_yemsq_patient_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PHQ010Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Somatoform disorders)",
                "verbose_name_plural": "PHQ Questions (Somatoform disorders)",
            },
        ),
        migrations.CreateModel(
            name="PHQ011Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Somatoform disorders - Severity)",
                "verbose_name_plural": "PHQ Questions (Somatoform disorders - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ020Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Depressive disorders)",
                "verbose_name_plural": "PHQ Questions (Depressive disorders)",
            },
        ),
        migrations.CreateModel(
            name="PHQ021Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Depressive disorders - Severity)",
                "verbose_name_plural": "PHQ Questions (Depressive disorders - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ030Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Panic disorder - part 1)",
                "verbose_name_plural": "PHQ Questions (Panic disorder - part 1)",
            },
        ),
        migrations.CreateModel(
            name="PHQ040Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Panic disorder - part 2)",
                "verbose_name_plural": "PHQ Questions (Panic disorder - part 2)",
            },
        ),
        migrations.CreateModel(
            name="PHQ041Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Panic disorder - Severity)",
                "verbose_name_plural": "PHQ Questions (Panic disorder - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ050Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Anxiety disorders)",
                "verbose_name_plural": "PHQ Questions (Anxiety disorders)",
            },
        ),
        migrations.CreateModel(
            name="PHQ051Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Anxiety disorders - Severity)",
                "verbose_name_plural": "PHQ Questions (Anxiety disorders - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ060Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Eating disorders - part 1)",
                "verbose_name_plural": "PHQ Questions (Eating disorders - part 1)",
            },
        ),
        migrations.CreateModel(
            name="PHQ070Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Eating disorders - part 2)",
                "verbose_name_plural": "PHQ Questions (Eating disorders - part 2)",
            },
        ),
        migrations.CreateModel(
            name="PHQ080Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Eating disorders - part 3)",
                "verbose_name_plural": "PHQ Questions (Eating disorders - part 3)",
            },
        ),
        migrations.CreateModel(
            name="PHQ081Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Eating disorders - Severity)",
                "verbose_name_plural": "PHQ Questions (Eating disorders - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ090Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Alcohol consumption)",
                "verbose_name_plural": "PHQ Questions (Alcohol consumption)",
            },
        ),
        migrations.CreateModel(
            name="PHQ100Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Alcohol abuse disorder)",
                "verbose_name_plural": "PHQ Questions (Alcohol abuse disorder)",
            },
        ),
        migrations.CreateModel(
            name="PHQ101Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_question", models.TextField(verbose_name="سوال انگلیسی")),
                ("fa_question", models.TextField(verbose_name="سوال فارسی")),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
            ],
            options={
                "verbose_name": "PHQ Sheet (Alcohol abuse disorder - Severity)",
                "verbose_name_plural": "PHQ Questions (Alcohol abuse disorder - Severity)",
            },
        ),
        migrations.RenameField(
            model_name="mcscis",
            old_name="patient_id",
            new_name="patient",
        ),
        migrations.RenameField(
            model_name="yemsq",
            old_name="patient_id",
            new_name="patient",
        ),
        migrations.CreateModel(
            name="PHQ101",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Alcohol abuse disorder - Severity)",
                "verbose_name_plural": "PHQ Records (Alcohol abuse disorder - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ100",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Alcohol abuse disorder)",
                "verbose_name_plural": "PHQ Records (Alcohol abuse disorder)",
            },
        ),
        migrations.CreateModel(
            name="PHQ090",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Alcohol consumption)",
                "verbose_name_plural": "PHQ Records (Alcohol consumption)",
            },
        ),
        migrations.CreateModel(
            name="PHQ081",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Eating disorders - Severity)",
                "verbose_name_plural": "PHQ Records (Eating disorders - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ080",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Eating disorders - part 3)",
                "verbose_name_plural": "PHQ Records (Eating disorders - part 3)",
            },
        ),
        migrations.CreateModel(
            name="PHQ070",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "q_3",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 3"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Eating disorders - part 2)",
                "verbose_name_plural": "PHQ Records (Eating disorders - part 2)",
            },
        ),
        migrations.CreateModel(
            name="PHQ060",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Eating disorders - part 1)",
                "verbose_name_plural": "PHQ Records (Eating disorders - part 1)",
            },
        ),
        migrations.CreateModel(
            name="PHQ051",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Anxiety disorders - Severity)",
                "verbose_name_plural": "PHQ Records (Anxiety disorders - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ050",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "q_3",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 3"
                    ),
                ),
                (
                    "q_4",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 4"
                    ),
                ),
                (
                    "q_5",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 5"
                    ),
                ),
                (
                    "q_6",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 6"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Anxiety disorders)",
                "verbose_name_plural": "PHQ Records (Anxiety disorders)",
            },
        ),
        migrations.CreateModel(
            name="PHQ041",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Panic disorder - Severity)",
                "verbose_name_plural": "PHQ Records (Panic disorder - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ040",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "q_3",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 3"
                    ),
                ),
                (
                    "q_4",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 4"
                    ),
                ),
                (
                    "q_5",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 5"
                    ),
                ),
                (
                    "q_6",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 6"
                    ),
                ),
                (
                    "q_7",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 7"
                    ),
                ),
                (
                    "q_8",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 8"
                    ),
                ),
                (
                    "q_9",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 9"
                    ),
                ),
                (
                    "q_10",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 10"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Panic disorder - part 2)",
                "verbose_name_plural": "PHQ Records (Panic disorder - part 2)",
            },
        ),
        migrations.CreateModel(
            name="PHQ030",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "q_3",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 3"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Panic disorder - part 1)",
                "verbose_name_plural": "PHQ Records (Panic disorder - part 1)",
            },
        ),
        migrations.CreateModel(
            name="PHQ021",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Depressive disorders - Severity)",
                "verbose_name_plural": "PHQ Records (Depressive disorders - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ020",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "q_3",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 3"
                    ),
                ),
                (
                    "q_4",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 4"
                    ),
                ),
                (
                    "q_5",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 5"
                    ),
                ),
                (
                    "q_6",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 6"
                    ),
                ),
                (
                    "q_7",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 7"
                    ),
                ),
                (
                    "q_8",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 8"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Depressive disorders)",
                "verbose_name_plural": "PHQ Records (Depressive disorders)",
            },
        ),
        migrations.CreateModel(
            name="PHQ011",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Somatoform disorders - Severity)",
                "verbose_name_plural": "PHQ Records (Somatoform disorders - Severity)",
            },
        ),
        migrations.CreateModel(
            name="PHQ010",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "q_3",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 3"
                    ),
                ),
                (
                    "q_4",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 4"
                    ),
                ),
                (
                    "q_5",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 5"
                    ),
                ),
                (
                    "q_6",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 6"
                    ),
                ),
                (
                    "q_7",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 7"
                    ),
                ),
                (
                    "q_8",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 8"
                    ),
                ),
                (
                    "q_9",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 9"
                    ),
                ),
                (
                    "q_10",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 10"
                    ),
                ),
                (
                    "q_11",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 11"
                    ),
                ),
                (
                    "q_12",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 12"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شمارۀ پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "PHQ Record (Somatoform disorders)",
                "verbose_name_plural": "PHQ Records (Somatoform disorders)",
            },
        ),
    ]
