# Generated by Django 4.2.8 on 2025-05-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentaccesslog",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentaccesslog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="permissionprotocol",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="protocolassignment",
            name="protocol",
        ),
        migrations.AlterUniqueTogether(
            name="protocolgrouppermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="protocolgrouppermission",
            name="flags",
        ),
        migrations.RemoveField(
            model_name="protocolgrouppermission",
            name="group",
        ),
        migrations.RemoveField(
            model_name="protocolgrouppermission",
            name="protocol",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="DocumentAccessLog",
        ),
        migrations.DeleteModel(
            name="FileExtension",
        ),
        migrations.DeleteModel(
            name="PermissionFlag",
        ),
        migrations.DeleteModel(
            name="PermissionProtocol",
        ),
        migrations.DeleteModel(
            name="ProtocolAssignment",
        ),
        migrations.DeleteModel(
            name="ProtocolGroupPermission",
        ),
    ]
