# Generated by Django 4.2.8 on 2025-03-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0002_rename_lab_testmeta_id_meta_lab_testmeta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yemsq",
            name="patient_id",
        ),
        migrations.DeleteModel(
            name="YEMSQSheet",
        ),
        migrations.DeleteModel(
            name="YEMSQ",
        ),
    ]
