# Generated by Django 4.2.8 on 2025-03-10 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0023_rename_secretarytags_patient_secretarytags"),
        ("lab", "0029_alter_category_en_name_alter_cbc_performer_and_more"),
        ("questionnaires", "0003_remove_yemsq_patient_id_delete_yemsqsheet_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metaq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lowest",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="میزان حداقل"
                    ),
                ),
                ("vector", models.PositiveSmallIntegerField(verbose_name="Vector")),
                (
                    "highest",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="میزان حداکثر"
                    ),
                ),
                (
                    "instruction_en",
                    models.TextField(
                        verbose_name="دستورالعمل و معرفی پرسشنامه به انگلیسی"
                    ),
                ),
                (
                    "instruction_fa",
                    models.TextField(
                        verbose_name="دستورالعمل و معرفی پرسشنامه به فارسی"
                    ),
                ),
                (
                    "reference_article",
                    models.CharField(max_length=256, verbose_name="مقاله مرجع"),
                ),
                (
                    "validator_fa",
                    models.CharField(
                        max_length=256,
                        verbose_name="اعتبار سنجی پرسشنامه برای زبان فارسی توسط",
                    ),
                ),
                (
                    "level_1_en",
                    models.CharField(max_length=256, verbose_name="Level 1 in English"),
                ),
                (
                    "level_1_fa",
                    models.CharField(max_length=256, verbose_name="Level 1 in Persian"),
                ),
                (
                    "level_2_en",
                    models.CharField(max_length=256, verbose_name="Level 2 in English"),
                ),
                (
                    "level_2_fa",
                    models.CharField(max_length=256, verbose_name="Level 2 in Persian"),
                ),
                (
                    "level_3_en",
                    models.CharField(max_length=256, verbose_name="Level 3 in English"),
                ),
                (
                    "level_3_fa",
                    models.CharField(max_length=256, verbose_name="Level 3 in Persian"),
                ),
                (
                    "level_4_en",
                    models.CharField(max_length=256, verbose_name="Level 4 in English"),
                ),
                (
                    "level_4_fa",
                    models.CharField(max_length=256, verbose_name="Level 4 in Persian"),
                ),
                (
                    "level_5_en",
                    models.CharField(max_length=256, verbose_name="Level 5 in English"),
                ),
                (
                    "level_5_fa",
                    models.CharField(max_length=256, verbose_name="Level 5 in Persian"),
                ),
                (
                    "level_6_en",
                    models.CharField(max_length=256, verbose_name="Level 6 in English"),
                ),
                (
                    "level_6_fa",
                    models.CharField(max_length=256, verbose_name="Level 6 in Persian"),
                ),
                (
                    "level_7_en",
                    models.CharField(max_length=256, verbose_name="Level 7 in English"),
                ),
                (
                    "level_7_fa",
                    models.CharField(max_length=256, verbose_name="Level 7 in Persian"),
                ),
                (
                    "level_8_en",
                    models.CharField(max_length=256, verbose_name="Level 8 in English"),
                ),
                (
                    "level_8_fa",
                    models.CharField(max_length=256, verbose_name="Level 8 in Persian"),
                ),
                (
                    "level_9_en",
                    models.CharField(max_length=256, verbose_name="Level 9 in English"),
                ),
                (
                    "level_9_fa",
                    models.CharField(max_length=256, verbose_name="Level 9 in Persian"),
                ),
                (
                    "level_10_en",
                    models.CharField(
                        max_length=256, verbose_name="Level 10 in English"
                    ),
                ),
                (
                    "level_10_fa",
                    models.CharField(
                        max_length=256, verbose_name="Level 10 in Persian"
                    ),
                ),
                (
                    "lab_testmeta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lab.testmeta",
                        unique=True,
                        verbose_name="Lab Test Meta ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta",
                "verbose_name_plural": "Meta",
            },
        ),
        migrations.CreateModel(
            name="YEMSQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Date")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="زمان")),
                (
                    "q_1",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 1"
                    ),
                ),
                (
                    "q_2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 2"
                    ),
                ),
                (
                    "q_3",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 3"
                    ),
                ),
                (
                    "q_4",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 4"
                    ),
                ),
                (
                    "q_5",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 5"
                    ),
                ),
                (
                    "q_6",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 6"
                    ),
                ),
                (
                    "q_7",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 7"
                    ),
                ),
                (
                    "q_8",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 8"
                    ),
                ),
                (
                    "q_9",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 9"
                    ),
                ),
                (
                    "q_10",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 10"
                    ),
                ),
                (
                    "q_11",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 11"
                    ),
                ),
                (
                    "q_12",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 12"
                    ),
                ),
                (
                    "q_13",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 13"
                    ),
                ),
                (
                    "q_14",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 14"
                    ),
                ),
                (
                    "q_15",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 15"
                    ),
                ),
                (
                    "q_16",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 16"
                    ),
                ),
                (
                    "q_17",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 17"
                    ),
                ),
                (
                    "q_18",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 18"
                    ),
                ),
                (
                    "q_19",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 19"
                    ),
                ),
                (
                    "q_20",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 20"
                    ),
                ),
                (
                    "q_21",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 21"
                    ),
                ),
                (
                    "q_22",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 22"
                    ),
                ),
                (
                    "q_23",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 23"
                    ),
                ),
                (
                    "q_24",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 24"
                    ),
                ),
                (
                    "q_25",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 25"
                    ),
                ),
                (
                    "q_26",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 26"
                    ),
                ),
                (
                    "q_27",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 27"
                    ),
                ),
                (
                    "q_28",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 28"
                    ),
                ),
                (
                    "q_29",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 29"
                    ),
                ),
                (
                    "q_30",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 30"
                    ),
                ),
                (
                    "q_31",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 31"
                    ),
                ),
                (
                    "q_32",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 32"
                    ),
                ),
                (
                    "q_33",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 33"
                    ),
                ),
                (
                    "q_34",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 34"
                    ),
                ),
                (
                    "q_35",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 35"
                    ),
                ),
                (
                    "q_36",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 36"
                    ),
                ),
                (
                    "q_37",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 37"
                    ),
                ),
                (
                    "q_38",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 38"
                    ),
                ),
                (
                    "q_39",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 39"
                    ),
                ),
                (
                    "q_40",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 40"
                    ),
                ),
                (
                    "q_41",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 41"
                    ),
                ),
                (
                    "q_42",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 42"
                    ),
                ),
                (
                    "q_43",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 43"
                    ),
                ),
                (
                    "q_44",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 44"
                    ),
                ),
                (
                    "q_45",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 45"
                    ),
                ),
                (
                    "q_46",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 46"
                    ),
                ),
                (
                    "q_47",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 47"
                    ),
                ),
                (
                    "q_48",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 48"
                    ),
                ),
                (
                    "q_49",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 49"
                    ),
                ),
                (
                    "q_50",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 50"
                    ),
                ),
                (
                    "q_51",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 51"
                    ),
                ),
                (
                    "q_52",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 52"
                    ),
                ),
                (
                    "q_53",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 53"
                    ),
                ),
                (
                    "q_54",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 54"
                    ),
                ),
                (
                    "q_55",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 55"
                    ),
                ),
                (
                    "q_56",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 56"
                    ),
                ),
                (
                    "q_57",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 57"
                    ),
                ),
                (
                    "q_58",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 58"
                    ),
                ),
                (
                    "q_59",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 59"
                    ),
                ),
                (
                    "q_60",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 60"
                    ),
                ),
                (
                    "q_61",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 61"
                    ),
                ),
                (
                    "q_62",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 62"
                    ),
                ),
                (
                    "q_63",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 63"
                    ),
                ),
                (
                    "q_64",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 64"
                    ),
                ),
                (
                    "q_65",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 65"
                    ),
                ),
                (
                    "q_66",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 66"
                    ),
                ),
                (
                    "q_67",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 67"
                    ),
                ),
                (
                    "q_68",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 68"
                    ),
                ),
                (
                    "q_69",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 69"
                    ),
                ),
                (
                    "q_70",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 70"
                    ),
                ),
                (
                    "q_71",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 71"
                    ),
                ),
                (
                    "q_72",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 72"
                    ),
                ),
                (
                    "q_73",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 73"
                    ),
                ),
                (
                    "q_74",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 74"
                    ),
                ),
                (
                    "q_75",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Question 75"
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.patient",
                        verbose_name="شماره پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "YEMSQ Record",
                "verbose_name_plural": "YEMSQ Records",
            },
        ),
        migrations.CreateModel(
            name="YEMSQSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
                (
                    "subscore",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="نمره بخش"
                    ),
                ),
            ],
            options={
                "verbose_name": "YEMSQ Sheet",
                "verbose_name_plural": "YEMSQ Sheets",
            },
        ),
    ]
