# Generated by Django 4.2.8 on 2025-03-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0008_metaque_delete_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="YEMSQSheets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coefficient", models.SmallIntegerField(verbose_name="ضریب")),
                (
                    "subscore",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="نمره بخش"
                    ),
                ),
            ],
            options={
                "verbose_name": "YEMSQ Sheet",
                "verbose_name_plural": "YEMSQ Sheets",
            },
        ),
        migrations.DeleteModel(
            name="YEMSQSheet",
        ),
    ]
