# Generated by Django 4.2.8 on 2025-03-11 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0010_yemsqsheet_delete_yemsqsheets"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YEMSQSheet",
        ),
    ]
