# Generated by Django 4.2.8 on 2025-03-11 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0029_alter_category_en_name_alter_cbc_performer_and_more"),
        ("questionnaires", "0012_yemsqsheet"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Metaque",
            new_name="Meta",
        ),
    ]
