# Generated by Django 4.2.8 on 2025-03-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0014_mcscissheet_alter_yemsqsheet_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mcscissheet",
            options={
                "verbose_name": "پرسشنامه غربالگری حافظه",
                "verbose_name_plural": "پرسشنامه غربالگری حافظه",
            },
        ),
        migrations.AlterModelOptions(
            name="yemsqsheet",
            options={
                "verbose_name": "پرسشنامه طرحواره های ناسازگار اولیه یانگ",
                "verbose_name_plural": "سوالات پرسشنامه طرحواره های ناسازگار اولیه یانگ",
            },
        ),
        migrations.AlterField(
            model_name="mcscissheet",
            name="subscore",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="نمره بخش"
            ),
        ),
        migrations.AlterField(
            model_name="yemsqsheet",
            name="subscore",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="نمره بخش"
            ),
        ),
    ]
