# Generated by Django 4.2.8 on 2025-03-13 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "questionnaires",
            "0015_alter_mcscissheet_options_alter_yemsqsheet_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mcscissheet",
            name="subscore",
        ),
        migrations.RemoveField(
            model_name="yemsqsheet",
            name="subscore",
        ),
        migrations.AddField(
            model_name="mcscissheet",
            name="category_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Category Content Type",
            ),
        ),
        migrations.AddField(
            model_name="mcscissheet",
            name="category_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="yemsqsheet",
            name="category_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Category Content Type",
            ),
        ),
        migrations.AddField(
            model_name="yemsqsheet",
            name="category_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
