# Generated by Django 4.2.8 on 2025-03-13 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0018_yemsqcategoris_alter_yemsqsheet_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="YEMSQCategoris",
            new_name="YEMSQCategories",
        ),
        migrations.RemoveField(
            model_name="mcscissheet",
            name="category_content_type",
        ),
        migrations.RemoveField(
            model_name="mcscissheet",
            name="category_object_id",
        ),
        migrations.RemoveField(
            model_name="yemsqsheet",
            name="category_content_type",
        ),
        migrations.RemoveField(
            model_name="yemsqsheet",
            name="category_object_id",
        ),
        migrations.AddField(
            model_name="yemsqsheet",
            name="Category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaires.yemsqcategories",
                verbose_name="نمره بخش",
            ),
        ),
    ]
