# Generated by Django 4.2.8 on 2025-04-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0028_patient_patient_id_alternative"),
        ("questionnaires", "0020_alter_yemsqcategories_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcscis",
            name="patient_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="identity.patient",
                verbose_name="شمارۀ پرونده",
            ),
        ),
        migrations.AlterField(
            model_name="yemsq",
            name="patient_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="identity.patient",
                verbose_name="شمارۀ پرونده",
            ),
        ),
    ]
