# Generated by Django 4.2.8 on 2025-02-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0072_ticket_repo_url_alter_ticket_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="canonical_url",
        ),
    ]
